import type { Course } from "@/lib/types";

export const creditDebtCourse: Course = {
  id: "credit-debt",
  title: "Credit & Debt",
  tagline: "Learn how credit scores, interest, and loans actually work before they cost you real money.",
  description:
    "Most students get their first credit card or student loan with zero training on how either one works. This course breaks down credit scores, APR, minimum payments, and student loans using real numbers, so you can build credit on purpose instead of stumbling into debt.",
  category: "Money",
  icon: "CreditCard",
  color: "from-sky-400 to-violet-500",
  accent: "sky-300",
  order: 2,
  unlockLevel: 1,
  units: [
    // ────────────────────────────────────────────────────────────────
    // UNIT 1: Credit 101
    // ────────────────────────────────────────────────────────────────
    {
      id: "credit-debt-u1",
      courseId: "credit-debt",
      order: 1,
      title: "Credit 101",
      subtitle: "What a credit score is and why you probably don't have one yet",
      lessons: [
        {
          id: "credit-debt-u1-l1",
          unitId: "credit-debt-u1",
          courseId: "credit-debt",
          order: 1,
          title: "Why You Have No Credit (Yet)",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "What credit actually is and why turning 18 doesn't give you any.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u1-l1-t1",
              title: "Credit is a track record, not a number you're born with",
              body: "Credit is basically a report card on how reliably you pay back money you've borrowed. If you've never borrowed anything, no card, no loan, there's no history to score, so you start with a blank file, not a bad one.",
              example: "A freshman with zero cards and a freshman with a maxed-out card both look risky to a lender, but for opposite reasons: no data vs. bad data.",
            },
            {
              kind: "teach",
              id: "credit-debt-u1-l1-t2",
              title: "Why it matters before you think you need it",
              body: "Landlords, cell phone carriers, and even some employers check credit. Building a thin, positive history now means better apartment approvals and lower deposits later, not just cheaper loans.",
              analogy: "It's like a reference list for a job: you can't hand one over on day one, but you can start collecting good references immediately.",
            },
            {
              // Introduces every term the match question below tests. Without
              // this card the quiz asked learners to define APR, minimum payment
              // and utilization before the course had ever mentioned them.
              kind: "teach",
              id: "credit-debt-u1-l1-t3",
              title: "The four words on every credit card statement",
              body: "Before you open anything, learn the vocabulary. Your credit score is the number lenders use to judge how reliably you pay people back. APR is the yearly interest rate you're charged on any balance you don't pay off. The minimum payment is the smallest amount you can pay to keep the account in good standing. Utilization is how much of your credit limit you're currently using, your balance divided by your limit.",
              example: "A $500 limit with a $100 balance is 20% utilization. Pay $35 (the minimum) and you stay current, but the other $65 starts collecting interest at your APR.",
              analogy: "Score is your reputation, APR is the rent you pay on borrowed money, the minimum is the smallest rent check they'll accept, and utilization is how full your tank already is.",
            },
            {
              kind: "question",
              id: "credit-debt-u1-l1-qm",
              type: "match",
              prompt: "Match each credit term to what it means.",
              pairs: [
                { left: "APR", right: "The yearly interest rate on a balance you carry" },
                { left: "Credit score", right: "A number lenders use to judge your reliability" },
                { left: "Minimum payment", right: "The smallest amount due to stay current" },
                { left: "Utilization", right: "How much of your credit limit you're using" },
              ],
              explanation:
                "APR is the cost of carrying a balance; your credit score summarizes your track record; the minimum payment keeps the account current (but barely dents the balance); utilization is your balance ÷ limit, keeping it low helps your score.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l1-q1",
              type: "true-false",
              prompt: "Having no credit history at all is treated the same as having bad credit.",
              correctBool: false,
              explanation: "No credit history just means lenders have no data on you yet, it's a blank slate, not a red flag like missed payments or high debt.",
              hint: "Think about the difference between 'unknown' and 'risky.'",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l1-q2",
              type: "mcq",
              prompt: "Which of these is NOT something a credit history helps with?",
              options: [
                "Getting approved for an apartment with a lower deposit",
                "Qualifying for a lower interest rate on a car loan",
                "Getting a higher grade in your finance class",
                "Getting approved for some jobs that run credit checks",
              ],
              correctIndex: 2,
              explanation: "Credit history affects borrowing, housing, and sometimes hiring decisions, but it has nothing to do with your grades.",
              hint: "One of these has nothing to do with money at all.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l1-q3",
              type: "scenario",
              prompt: "What's the smartest first move for Maya?",
              context: "Maya just turned 18 and wants an apartment off campus next year. She's never had a credit card or loan of any kind.",
              options: [
                "Wait until she needs the apartment to worry about credit",
                "Open a student or secured credit card now and use it lightly",
                "Avoid credit entirely so she never risks debt",
                "Ask her landlord to skip the credit check",
              ],
              correctIndex: 1,
              explanation: "Starting a small, manageable credit line early gives Maya months of positive history built up by the time she actually needs it for an apartment.",
              hint: "Credit history takes time to build, starting early is the advantage.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u1-l2",
          unitId: "credit-debt-u1",
          courseId: "credit-debt",
          order: 2,
          title: "The 5 Ingredients of Your Score",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 30,
          summary: "The five factors that make up a FICO score, and how much each one actually counts.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u1-l2-t1",
              title: "Your score is a weighted recipe, not one number",
              body: "FICO scores blend five factors: payment history (35%), credit utilization (30%), length of credit history (15%), credit mix (10%), and new credit inquiries (10%). Payment history and utilization together make up nearly two-thirds of your score.",
              example: "Paying every bill on time but maxing out your card will still hurt you, because utilization is 30% of the formula on its own.",
            },
            {
              kind: "teach",
              id: "credit-debt-u1-l2-t2",
              title: "Length of history rewards patience",
              body: "The 15% 'length of history' factor averages the age of all your accounts, which is why closing your very first card later can actually lower your score by shortening your average account age.",
              analogy: "It's like seniority at a job, showing up reliably for years counts for something that a new hire can't fake.",
            },
            {
              kind: "question",
              id: "credit-debt-u1-l2-q1",
              type: "mcq",
              prompt: "Which factor carries the MOST weight in a FICO score?",
              options: ["Credit mix", "New credit inquiries", "Payment history", "Length of credit history"],
              correctIndex: 2,
              explanation: "Payment history is 35% of your FICO score, the single biggest factor, because it directly predicts whether you'll pay back what you borrow.",
              hint: "It's the factor lenders care about most: do you pay on time?",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l2-q2",
              type: "fill-in",
              prompt: "Fill in the blank: Credit ______ measures how much of your available credit you're actually using, and makes up 30% of your score.",
              accept: ["utilization", "credit utilization"],
              explanation: "Credit utilization is your balance divided by your credit limit, keeping it low is the second-biggest lever you control.",
              hint: "It's the ratio between what you owe and your credit limit.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l2-q3",
              type: "true-false",
              prompt: "Credit mix and new credit inquiries each count for 10% of your FICO score.",
              correctBool: true,
              explanation: "Both credit mix (types of accounts you have) and new credit (recent applications) are worth 10% each, smaller factors, but not nothing.",
              hint: "These two are the smallest, and they're equal to each other.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l2-q4",
              type: "mcq",
              prompt: "Jordan closes the very first credit card he ever opened, which he'd had for 4 years. What's the most likely effect?",
              options: [
                "His score goes up because he has one less account to manage",
                "His score could drop because it lowers his average account age",
                "Nothing changes at all",
                "His score goes up because his utilization automatically improves",
              ],
              correctIndex: 1,
              explanation: "Closing your oldest account can shorten your average credit history length, which is 15% of your score, often a bad trade for a card with no annual fee.",
              hint: "Think about what happens to his 'average age of accounts' when the oldest one disappears.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u1-l3",
          unitId: "credit-debt-u1",
          courseId: "credit-debt",
          order: 3,
          title: "Reading the Score & Building It Safely",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 30,
          summary: "What the 300-850 range means in practice, and the low-risk ways students actually build credit.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u1-l3-t1",
              title: "The 300-850 scale in plain English",
              body: "FICO scores run 300-850. Roughly: below 580 is poor, 670 is the start of 'good,' 740 is 'very good' and unlocks the best rates, and 800+ is 'exceptional' with basically no further benefit for going higher.",
              example: "A score of 740 vs. 800 rarely changes your interest rate, but 620 vs. 700 can be the difference between approval and denial.",
            },
            {
              kind: "teach",
              id: "credit-debt-u1-l3-t2",
              title: "Three low-risk ways students build credit",
              body: "A secured card (backed by a cash deposit you control), becoming an authorized user on a parent's well-managed card, or a student credit card with a low limit are all beginner-safe ways to start a credit file without much downside.",
              analogy: "A secured card is like a security deposit for an apartment, you put money down, and it proves you're trustworthy without anyone taking on real risk.",
            },
            {
              kind: "question",
              id: "credit-debt-u1-l3-q1",
              type: "mcq",
              prompt: "A FICO score of 740 generally falls into which range?",
              options: ["Poor", "Fair", "Good", "Very good"],
              correctIndex: 3,
              explanation: "740 sits in the 'very good' range, typically qualifying for strong interest rates on loans and cards.",
              hint: "It's one tier below the top 'exceptional' range.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l3-q2",
              type: "scenario",
              prompt: "What should Devon do?",
              context: "Devon is 18 with no income yet and gets rejected for a regular credit card. His mom offers to add him as an authorized user on her credit card, which she's had for 10 years and always pays off in full.",
              options: [
                "Decline, because authorized user status doesn't affect his credit at all",
                "Accept, it can add years of positive history to his own credit file",
                "Accept, but only if he gets his own physical card to use immediately",
                "Decline, because it will hurt his mom's credit score",
              ],
              correctIndex: 1,
              explanation: "Becoming an authorized user on a long-standing, well-managed account can inherit that positive history onto Devon's file, jumpstarting his score without him needing to qualify on his own yet.",
              hint: "This only works well because the primary account has a long, clean payment history.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l3-q3",
              type: "fill-in",
              prompt: "Fill in the blank: A ______ card requires a cash deposit that typically becomes your credit limit, making it a low-risk way to start building credit.",
              accept: ["secured", "secured card", "secured credit card"],
              explanation: "Secured cards require a refundable deposit as collateral, which is why issuers approve them even for people with no credit history.",
              hint: "The deposit is what makes it low-risk for the bank.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u1-l4",
          unitId: "credit-debt-u1",
          courseId: "credit-debt",
          order: 4,
          title: "Unit 1 Challenge: Credit Fundamentals",
          difficulty: "Beginner",
          kind: "challenge",
          xp: 75,
          summary: "Prove you've got credit basics locked in: what it is, how it's scored, and how to build it safely.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u1-l4-t1",
              title: "Quick recap before the challenge",
              body: "Credit is a track record you build over time. Your score is 35% payment history, 30% utilization, 15% length, 10% mix, 10% new credit. Start safely with a secured card, authorized-user status, or a student card.",
            },
            {
              kind: "question",
              id: "credit-debt-u1-l4-q1",
              type: "mcq",
              prompt: "Two factors together make up 65% of a FICO score. Which two?",
              options: [
                "Credit mix and new credit",
                "Payment history and credit utilization",
                "Length of history and credit mix",
                "New credit and length of history",
              ],
              correctIndex: 1,
              explanation: "Payment history (35%) plus utilization (30%) equals 65%, together they're by far the biggest levers you control.",
              hint: "Add up the two biggest percentages from the five factors.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l4-q2",
              type: "true-false",
              prompt: "A score of 850 will get you meaningfully better loan terms than a score of 800.",
              correctBool: false,
              explanation: "Once you're in the 'exceptional' range (800+), lenders already offer their best terms, there's little to no practical benefit above that.",
              hint: "Think about diminishing returns at the very top of the scale.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l4-q3",
              type: "scenario",
              prompt: "What's the risk in Priya's plan?",
              context: "Priya, 19, has had one secured card for 8 months with perfect payments. She's considering closing it now that she qualifies for an unsecured student card, to 'clean up' her file.",
              options: [
                "There's no risk, more cards is always better",
                "Closing her oldest account could shorten her average credit age and hurt her score",
                "It will immediately raise her score by simplifying her file",
                "It has zero effect on her score either way",
              ],
              correctIndex: 1,
              explanation: "Even a short 8-month history is still her oldest account; closing it right after opening a new one can lower her average account age right when she needs it most.",
              hint: "Remember the length-of-history factor from lesson 2.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l4-q4",
              type: "fill-in",
              prompt: "Fill in the blank: Becoming an ______ ______ on a parent's old, well-managed card can inherit years of positive history.",
              accept: ["authorized user"],
              explanation: "Authorized user status lets you piggyback on someone else's account history, which is one of the fastest ways to build a credit file.",
              hint: "Two words, it's the status Devon considered in lesson 3.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u1-l4-q5",
              type: "mcq",
              prompt: "Which student is building credit the most safely?",
              options: [
                "Sam, who opened 4 cards in one month to 'maximize options'",
                "Ana, who uses a secured card for gas and pays it off in full every month",
                "Kai, who ignores his card statements since the limit is only $300",
                "Lee, who maxes out his student card every month but pays the minimum",
              ],
              correctIndex: 1,
              explanation: "Ana keeps utilization low, pays in full, and avoids unnecessary new-credit inquiries, the core habits that build a strong score safely.",
              hint: "Look for low utilization, on-time full payments, and no unnecessary new accounts.",
              xp: 15,
            },
          ],
        },
      ],
    },

    // ────────────────────────────────────────────────────────────────
    // UNIT 2: Cards Without the Trap
    // ────────────────────────────────────────────────────────────────
    {
      id: "credit-debt-u2",
      courseId: "credit-debt",
      order: 2,
      title: "Cards Without the Trap",
      subtitle: "APR, minimum payments, and utilization, the math that decides if a card helps or hurts you",
      lessons: [
        {
          id: "credit-debt-u2-l1",
          unitId: "credit-debt-u2",
          courseId: "credit-debt",
          order: 1,
          title: "What APR Actually Costs You",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "How APR turns an unpaid balance into real, compounding interest charges.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u2-l1-t1",
              title: "APR is the annual price of carrying a balance",
              body: "APR (Annual Percentage Rate) is the yearly interest rate charged on any balance you don't pay off. Credit cards typically divide it by 12 to charge interest monthly on whatever you still owe.",
              example: "A card with 24.99% APR charges roughly 2.08% per month, so a $500 balance left unpaid racks up about $10.40 in interest that very first month alone.",
            },
            {
              kind: "teach",
              id: "credit-debt-u2-l1-t2",
              title: "Interest compounds on interest",
              body: "If you don't pay off the interest either, next month's charge is calculated on the original balance PLUS the interest already added, so the balance can grow even if you stop spending entirely.",
              analogy: "It's like a snowball rolling downhill: it doesn't just stay the same size, it picks up more snow the longer it rolls.",
            },
            {
              kind: "question",
              id: "credit-debt-u2-l1-q1",
              type: "mcq",
              prompt: "A card has 24.99% APR. Roughly what's the monthly interest rate?",
              options: ["About 0.5%", "About 2.08%", "About 12.5%", "About 24.99%"],
              correctIndex: 1,
              explanation: "24.99% divided by 12 months is roughly 2.08% charged per month on your unpaid balance.",
              hint: "Divide the annual rate by 12 months.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l1-q2",
              type: "true-false",
              prompt: "If you stop using your credit card completely, an unpaid balance can still grow because of interest.",
              correctBool: true,
              explanation: "Interest keeps accruing on whatever balance remains, regardless of whether you make new purchases, that's how balances balloon even after you stop spending.",
              hint: "Interest doesn't care whether you're still swiping the card.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l1-q3",
              type: "scenario",
              prompt: "About how much interest does Tyler's balance generate in the first month?",
              context: "Tyler put a $500 laptop charger and textbooks on his new credit card, which has a 24.99% APR. He doesn't pay it off right away.",
              options: ["About $1", "About $10", "About $50", "About $125"],
              correctIndex: 1,
              explanation: "At roughly 2.08% monthly (24.99% ÷ 12), a $500 balance generates about $10.40 in interest the first month, small-looking, but it adds up fast if unpaid.",
              hint: "Use the ~2.08% monthly rate from the previous question on $500.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u2-l2",
          unitId: "credit-debt-u2",
          courseId: "credit-debt",
          order: 2,
          title: "The Minimum Payment Trap",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 35,
          summary: "Why paying only the minimum keeps you in debt for years and costs far more than the sticker price.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u2-l2-t1",
              title: "Minimum payments are designed to be small",
              body: "Minimum payments are usually 1-3% of your balance or a flat $25-35, whichever is higher, set low enough that most of it goes to interest, not the actual debt.",
              example: "On a $1,000 balance at 24.99% APR, paying only a $25 minimum each month can take over 5 years to pay off and cost several hundred dollars in interest.",
            },
            {
              kind: "teach",
              id: "credit-debt-u2-l2-t2",
              title: "Paying more than the minimum is the single biggest lever",
              body: "Doubling or tripling your payment above the minimum dramatically cuts both the payoff time and the total interest paid, because more of each payment attacks the principal balance instead of just covering interest.",
              analogy: "Minimum payments are like only mowing the tips of overgrown grass, it looks handled, but the roots (the real balance) barely shrink.",
            },
            {
              kind: "question",
              id: "credit-debt-u2-l2-q1",
              type: "scenario",
              prompt: "What's the biggest problem with Chloe's plan?",
              context: "Chloe has a $1,000 credit card balance at 24.99% APR. She plans to pay the $25 minimum every month and figures she'll be debt-free within a year or two.",
              options: [
                "There's no problem, $25 a month easily clears $1,000",
                "At that rate it could take 5+ years and cost hundreds in extra interest",
                "The card company will forgive the balance after a year",
                "Minimum payments don't include interest at all",
              ],
              correctIndex: 1,
              explanation: "Because most of each $25 minimum payment covers interest rather than principal, a $1,000 balance at 24.99% APR paid at the minimum can take years to clear and cost far more than $1,000 total.",
              hint: "Remember minimum payments are designed to be small, most of the payment goes toward interest, not principal.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l2-q2",
              type: "true-false",
              prompt: "Paying double the minimum payment each month can meaningfully cut both your payoff time and total interest paid.",
              correctBool: true,
              explanation: "Extra payments go directly toward the principal, which shrinks the balance interest is calculated on, speeding up payoff and reducing total interest.",
              hint: "More money toward principal means less balance left to charge interest on.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l2-q3",
              type: "mcq",
              prompt: "Minimum payments are typically calculated as roughly what percentage of your balance?",
              options: ["10-15%", "1-3%", "25-30%", "50%"],
              correctIndex: 1,
              explanation: "Minimum payments are usually set around 1-3% of the balance (or a small flat fee), which is why they barely dent the principal.",
              hint: "It's a small slice, small enough that interest eats most of it.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l2-q4",
              type: "fill-in",
              prompt: "Fill in the blank: The remaining amount you owe on a card, separate from interest charges, is called the ______.",
              accept: ["principal", "balance", "principal balance"],
              explanation: "The principal is the actual amount borrowed or charged, interest is calculated on top of it, and extra payments should target it directly.",
              hint: "It's the 'real' debt, not the interest charged on top of it.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u2-l3",
          unitId: "credit-debt-u2",
          courseId: "credit-debt",
          order: 3,
          title: "Utilization, Grace Periods & Rewards",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 35,
          summary: "How to use a card in a way that helps your score instead of quietly wrecking it.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u2-l3-t1",
              title: "Keep utilization under 30%, lower is better",
              body: "Utilization is your balance divided by your limit. Experts generally suggest staying under 30% of your limit, and under 10% is even better for your score, since a small limit fills up fast.",
              example: "A $200 limit card is 'maxed' at just a $60 balance if you want to stay under 30%, one textbook can blow past that instantly.",
            },
            {
              kind: "teach",
              id: "credit-debt-u2-l3-t2",
              title: "Grace periods let you borrow interest-free",
              body: "A grace period is the window (often ~21-25 days) between your statement closing and your payment due date. Pay the full statement balance within that window and you owe zero interest, carry a balance past it, and interest starts accruing.",
              analogy: "It's like a free trial: use it fully (pay in full, on time) and there's no cost; miss the deadline and the charges kick in retroactively on some cards.",
            },
            {
              kind: "question",
              id: "credit-debt-u2-l3-q1",
              type: "scenario",
              prompt: "What should Ravi watch out for?",
              context: "Ravi has a student card with a $200 limit. He just charged a $70 textbook to it, and has no other balance this month.",
              options: [
                "Nothing, $70 is a small amount of money",
                "His utilization just hit 35%, above the recommended 30% threshold",
                "His limit will automatically increase to cover it",
                "The purchase has no effect on his utilization",
              ],
              correctIndex: 1,
              explanation: "$70 out of a $200 limit is 35% utilization, over the commonly recommended 30% ceiling, even though $70 feels like a small purchase.",
              hint: "Divide the balance by the limit: 70 ÷ 200.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l3-q2",
              type: "fill-in",
              prompt: "Fill in the blank: The window after your statement closes where you can pay in full and owe zero interest is called the ______ period.",
              accept: ["grace"],
              explanation: "The grace period is your interest-free window, paying the full statement balance by the due date means you never pay a cent of interest.",
              hint: "It's a period of leniency before interest kicks in.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l3-q3",
              type: "true-false",
              prompt: "Credit card rewards (like cash back) are worth chasing even if it means carrying a balance and paying interest.",
              correctBool: false,
              explanation: "Interest charges (often 20%+ APR) almost always outweigh rewards earned (typically 1-5% back), rewards only make sense if you pay your balance in full every month.",
              hint: "Compare a typical rewards rate to a typical APR, which number is bigger?",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l3-q4",
              type: "mcq",
              prompt: "Which habit best protects both your credit score and your wallet?",
              options: [
                "Spend up to the limit each month to 'use' the card fully",
                "Keep balances low relative to the limit and pay the statement in full each month",
                "Only make the minimum payment so more cash stays free",
                "Apply for several new cards each semester to raise total available credit fast",
              ],
              correctIndex: 1,
              explanation: "Low utilization plus paying in full inside the grace period means no interest charges and a strong utilization ratio, the combination that helps your score without costing you money.",
              hint: "Think about what protects utilization AND avoids interest at the same time.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u2-l4",
          unitId: "credit-debt-u2",
          courseId: "credit-debt",
          order: 4,
          title: "Unit 2 Challenge: Cards & Interest",
          difficulty: "Intermediate",
          kind: "challenge",
          xp: 85,
          summary: "Test your grasp of APR, minimum payments, utilization, and grace periods with harder scenarios.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u2-l4-t1",
              title: "Quick recap before the challenge",
              body: "APR is charged monthly on unpaid balances and compounds. Minimum payments barely touch principal. Keep utilization under 30% (ideally under 10%). Pay in full within the grace period to avoid interest entirely.",
            },
            {
              kind: "question",
              id: "credit-debt-u2-l4-q1",
              type: "scenario",
              prompt: "What's the single best move for Nia?",
              context: "Nia has a $600 balance on a card with 22% APR and a $2,000 limit. She has $600 in savings and is deciding what to do before her statement closes in 3 days.",
              options: [
                "Do nothing, her utilization is fine at 30%",
                "Pay the full $600 before the statement closes to avoid interest and lower reported utilization",
                "Only pay the minimum and save the rest for emergencies",
                "Move the balance to a new card with a lower limit",
              ],
              correctIndex: 1,
              explanation: "Paying the balance in full before the statement closes avoids interest charges entirely and reports a lower utilization to the bureaus, the strongest move available with cash on hand.",
              hint: "Think about both the interest angle and the utilization angle at once.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l4-q2",
              type: "mcq",
              prompt: "A $2,000 limit card has a $560 balance. What's the utilization, and is it in the safe zone?",
              options: [
                "28%, under the 30% guideline",
                "56%, well over the 30% guideline",
                "5.6%, very safe",
                "80%, extremely risky",
              ],
              correctIndex: 0,
              explanation: "560 ÷ 2000 = 28%, which is just under the commonly recommended 30% ceiling.",
              hint: "Divide balance by limit, then convert to a percentage.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l4-q3",
              type: "true-false",
              prompt: "As long as you eventually pay off a credit card balance, it doesn't matter how long it takes.",
              correctBool: false,
              explanation: "Timing matters a lot, the longer a balance sits unpaid, the more interest compounds, meaning slow payoff can cost far more than the original purchase price.",
              hint: "Think about compounding interest over years versus months.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l4-q4",
              type: "fill-in",
              prompt: "Fill in the blank: The annual interest rate a card charges on unpaid balances is called the ______.",
              accept: ["apr", "annual percentage rate"],
              explanation: "APR (Annual Percentage Rate) is the yearly cost of borrowing, typically divided by 12 to calculate the monthly interest charge on your balance.",
              hint: "It's the three-letter acronym from lesson 1.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u2-l4-q5",
              type: "scenario",
              prompt: "Which student is handling their card in the smartest way?",
              context: "Four roommates each have a credit card. Owen pays the minimum and keeps spending. Bea maxes her card for a $900 spring break trip. Sam pays his statement in full every month and keeps utilization under 10%. Priya has 5 cards she opened this year to 'build credit fast.'",
              options: ["Owen", "Bea", "Sam", "Priya"],
              correctIndex: 2,
              explanation: "Sam avoids interest entirely by paying in full and keeps utilization low, which builds credit steadily without the risk or cost the other three are taking on.",
              hint: "Look for who avoids both interest charges and high utilization.",
              xp: 15,
            },
          ],
        },
      ],
    },

    // ────────────────────────────────────────────────────────────────
    // UNIT 3: Student Loans & Debt Payoff
    // ────────────────────────────────────────────────────────────────
    {
      id: "credit-debt-u3",
      courseId: "credit-debt",
      order: 3,
      title: "Student Loans & Debt Payoff",
      subtitle: "Federal loans, interest capitalization, and how to actually dig out of debt",
      lessons: [
        {
          id: "credit-debt-u3-l1",
          unitId: "credit-debt-u3",
          courseId: "credit-debt",
          order: 1,
          title: "Subsidized vs. Unsubsidized Loans",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 30,
          summary: "The difference between federal loan types and who pays interest while you're still in school.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u3-l1-t1",
              title: "Subsidized: the government covers interest in school",
              body: "With subsidized federal loans, the government pays the interest while you're enrolled at least half-time, during your grace period, and during deferment. The loan balance stays exactly where it started until repayment begins.",
              example: "Borrow $3,500 subsidized freshman year, and it's still $3,500 when repayment starts, no interest was added while you were in school.",
            },
            {
              kind: "teach",
              id: "credit-debt-u3-l1-t2",
              title: "Unsubsidized: interest accrues the whole time",
              body: "Unsubsidized loans start accruing interest from the day they're disbursed, even while you're in school, you're just not required to pay it yet. That unpaid interest can later get added to your balance.",
              analogy: "Subsidized is like a parking meter that's paused while you're in class; unsubsidized keeps ticking the whole time, you just don't have to feed it coins yet.",
            },
            {
              kind: "question",
              id: "credit-debt-u3-l1-q1",
              type: "mcq",
              prompt: "Who pays the interest on a subsidized federal loan while you're in school at least half-time?",
              options: ["You, immediately", "The government", "Your school", "No interest accrues for anyone"],
              correctIndex: 1,
              explanation: "The federal government covers interest on subsidized loans during in-school enrollment, the grace period, and deferment periods.",
              hint: "This is exactly what the word 'subsidized' means here.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l1-q2",
              type: "true-false",
              prompt: "Unsubsidized loans accrue interest while you're still in school, even though you don't have to pay it yet.",
              correctBool: true,
              explanation: "Interest begins accruing on unsubsidized loans from disbursement, regardless of enrollment status, it just isn't due until later.",
              hint: "The clock starts immediately, even if payment doesn't.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l1-q3",
              type: "scenario",
              prompt: "Which loan type is generally more favorable for Marcus, all else equal?",
              context: "Marcus qualifies for both a subsidized and an unsubsidized federal loan of the same amount for this school year and needs to pick which to prioritize taking first.",
              options: [
                "Unsubsidized, because it has a lower interest rate",
                "Subsidized, because the government covers interest while he's in school",
                "They're identical in every way",
                "Unsubsidized, because it doesn't need to be repaid",
              ],
              correctIndex: 1,
              explanation: "Subsidized loans don't accrue interest while you're in school, making them the cheaper option to prioritize when both are available in equal amounts.",
              hint: "Which one avoids interest piling up before repayment even starts?",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u3-l2",
          unitId: "credit-debt-u3",
          courseId: "credit-debt",
          order: 2,
          title: "Capitalization: When Interest Becomes Debt",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "How unpaid interest gets added to your loan balance, and why that permanently raises what you owe.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u3-l2-t1",
              title: "Capitalization adds interest to your principal",
              body: "Capitalization happens when unpaid interest gets added to your loan's principal balance, usually at the end of your grace period or after deferment ends. After that, you're charged interest on a bigger number, including interest on what used to be just interest.",
              example: "Borrow $5,500 unsubsidized at 6.53% APR for 4 years of school plus a 6-month grace period: roughly $1,600+ in accrued interest can capitalize, pushing your real starting balance well above $7,000.",
            },
            {
              kind: "teach",
              id: "credit-debt-u3-l2-t2",
              title: "You can prevent it by paying interest early",
              body: "Even small interest-only payments while you're in school stop that interest from capitalizing later, keeping your principal exactly at the amount you actually borrowed.",
              analogy: "It's like paying off a credit card's interest charge each month so it never rolls into a bigger balance next month.",
            },
            {
              kind: "question",
              id: "credit-debt-u3-l2-q1",
              type: "fill-in",
              prompt: "Fill in the blank: When unpaid interest gets added to your loan's principal balance, this is called ______.",
              accept: ["capitalization", "interest capitalization"],
              explanation: "Capitalization folds accrued interest into your principal, so future interest is calculated on a larger balance going forward.",
              hint: "It's the term used throughout this lesson's title.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l2-q2",
              type: "scenario",
              prompt: "About how much could Elena's real starting balance be after capitalization?",
              context: "Elena borrowed $5,500 in unsubsidized loans at 6.53% APR for her freshman year. Over 4 years of school plus a 6-month grace period, interest accrues and then capitalizes when repayment begins.",
              options: ["Exactly $5,500", "Around $5,600", "Over $7,000", "Over $15,000"],
              correctIndex: 2,
              explanation: "At 6.53% APR compounding over roughly 4.5 years of school and grace period, accrued interest on $5,500 can exceed $1,600, pushing the capitalized balance past $7,000.",
              hint: "Interest at 6.53% for over 4 years on $5,500 adds up to more than you'd guess.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l2-q3",
              type: "true-false",
              prompt: "Making small interest-only payments while still in school can prevent that interest from ever capitalizing.",
              correctBool: true,
              explanation: "Paying off accrued interest before it capitalizes keeps your principal balance from growing, saving money over the life of the loan.",
              hint: "If the interest is paid off, there's nothing left to add to the principal.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l2-q4",
              type: "mcq",
              prompt: "Why is capitalized interest worse than regular accrued interest?",
              options: [
                "It isn't worse, they're the same thing",
                "Because after capitalizing, you pay interest on interest, permanently raising your principal",
                "Because it only affects subsidized loans",
                "Because it lowers your interest rate automatically",
              ],
              correctIndex: 1,
              explanation: "Once interest capitalizes, it becomes part of the principal, so future interest is charged on that larger amount too, a compounding effect that costs more over time.",
              hint: "Think about what happens to future interest charges once the principal itself grows.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u3-l3",
          unitId: "credit-debt-u3",
          courseId: "credit-debt",
          order: 3,
          title: "Paying It Off: Avalanche, Snowball & Good vs. Toxic Debt",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Two proven payoff strategies, plus how to tell debt that builds your future from debt that traps you.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u3-l3-t1",
              title: "Avalanche vs. snowball",
              body: "The avalanche method pays extra toward your highest-interest debt first, saving the most money mathematically. The snowball method pays off your smallest balance first for a quick win, which can build momentum even though it costs a bit more in total interest.",
              example: "With a $500 card at 25% APR and a $3,000 loan at 7%, avalanche attacks the card first; snowball attacks the $500 balance first purely because it's smaller.",
            },
            {
              kind: "teach",
              id: "credit-debt-u3-l3-t2",
              title: "Not all debt is equally dangerous",
              body: "'Good' debt, like a federal student loan, typically funds something that increases your future earning power and has a relatively low, fixed interest rate. 'Toxic' debt, like a payday loan, can carry APRs around 300-400% and trap borrowers in repeat cycles.",
              analogy: "A student loan is like planting a tree that pays off for decades; a payday loan is like a leak that drains money faster than you can refill it.",
            },
            {
              kind: "question",
              id: "credit-debt-u3-l3-q1",
              type: "mcq",
              prompt: "Which payoff method mathematically saves the most total interest?",
              options: ["Snowball, always", "Avalanche, always", "They save exactly the same amount", "Neither, only the loan servicer decides"],
              correctIndex: 1,
              explanation: "Avalanche targets the highest-interest debt first, which minimizes the total interest paid across all your debts over time.",
              hint: "Think about which method attacks the most expensive debt first.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l3-q2",
              type: "true-false",
              prompt: "The snowball method can still be a smart choice even though it isn't the mathematically cheapest option.",
              correctBool: true,
              explanation: "Snowball's quick wins on small balances can build motivation and consistency, which matters if sticking with a payoff plan is the bigger challenge than optimizing every dollar.",
              hint: "Think about the psychological benefit versus the pure math.",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l3-q3",
              type: "scenario",
              prompt: "Why should Devon avoid the payday loan?",
              context: "Devon is $200 short on rent and sees a payday loan storefront advertising fast cash with an APR around 391%. He's considering it to cover the gap until his next paycheck.",
              options: [
                "He shouldn't avoid it, payday loans are treated like federal loans",
                "The APR is so extreme that even a short-term loan can spiral into a costly repeat-borrowing cycle",
                "Payday loans build credit history faster than any other option",
                "There's no real downside as long as he pays it back next week",
              ],
              correctIndex: 1,
              explanation: "At APRs in the hundreds of percent, even a 'quick' payday loan can generate fees and interest that trap borrowers into re-borrowing repeatedly to cover the last loan.",
              hint: "Compare 391% APR to the credit card APRs from Unit 2, how many times bigger is it?",
              xp: 10,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l3-q4",
              type: "fill-in",
              prompt: "Fill in the blank: The debt payoff method that targets the highest interest rate balance first is called the ______ method.",
              accept: ["avalanche"],
              explanation: "Avalanche prioritizes the costliest debt by interest rate, minimizing total interest paid across all balances.",
              hint: "It's named after something that comes down fast and hits the biggest thing first.",
              xp: 10,
            },
          ],
        },
        {
          id: "credit-debt-u3-l4",
          unitId: "credit-debt-u3",
          courseId: "credit-debt",
          order: 4,
          title: "Unit 3 Challenge: Loans & Payoff Strategy",
          difficulty: "Advanced",
          kind: "challenge",
          xp: 95,
          summary: "The hardest test yet: loan types, capitalization math, payoff strategy, and spotting toxic debt.",
          cards: [
            {
              kind: "teach",
              id: "credit-debt-u3-l4-t1",
              title: "Quick recap before the challenge",
              body: "Subsidized loans don't accrue interest in school; unsubsidized loans do. Unpaid interest can capitalize into your principal. Avalanche saves the most money; snowball builds momentum. Payday loans and other triple-digit-APR debt are toxic, avoid them.",
            },
            {
              kind: "question",
              id: "credit-debt-u3-l4-q1",
              type: "scenario",
              prompt: "What's the most cost-effective order for Priya to attack her debts?",
              context: "Priya graduated with a $6,000 federal loan at 5.5% APR and an $800 credit card balance at 26% APR. She has $150 extra per month beyond minimum payments on both.",
              options: [
                "Put all extra money toward the $6,000 loan first",
                "Split the extra evenly between both debts",
                "Put all extra money toward the $800 credit card first",
                "Ignore both and save the $150 instead",
              ],
              correctIndex: 2,
              explanation: "The avalanche method says attack the highest-interest debt first, the 26% APR credit card is costing her far more per dollar than the 5.5% loan, so clearing it first minimizes total interest.",
              hint: "Compare the two interest rates, which one is bleeding more money each month?",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l4-q2",
              type: "true-false",
              prompt: "A federal student loan and a payday loan should generally be treated as equally risky forms of debt.",
              correctBool: false,
              explanation: "Federal student loans carry fixed, relatively low rates and fund future earning potential, while payday loans carry APRs in the hundreds of percent and are far more likely to trap borrowers in a debt cycle.",
              hint: "Recall the 'good debt vs. toxic debt' comparison from lesson 3.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l4-q3",
              type: "mcq",
              prompt: "Sam has an unsubsidized loan and doesn't pay any interest during school. What happens at the end of his grace period?",
              options: [
                "Nothing, unsubsidized loans never charge interest",
                "The accrued interest is forgiven automatically",
                "The accrued interest capitalizes, becoming part of his principal balance",
                "His interest rate drops to 0% once repayment begins",
              ],
              correctIndex: 2,
              explanation: "Unpaid interest on an unsubsidized loan typically capitalizes at the end of the grace period, permanently increasing the principal he'll pay interest on going forward.",
              hint: "Think back to what 'capitalization' means and when it typically triggers.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l4-q4",
              type: "fill-in",
              prompt: "Fill in the blank: Paying off your smallest balance first, regardless of interest rate, to build motivation is called the ______ method.",
              accept: ["snowball"],
              explanation: "Snowball prioritizes small wins over pure math, which can help some borrowers stay consistent even though it isn't always the cheapest path.",
              hint: "It's named after something that starts small and builds up as it rolls.",
              xp: 15,
            },
            {
              kind: "question",
              id: "credit-debt-u3-l4-q5",
              type: "scenario",
              prompt: "What's the smartest move for Aisha right after graduation?",
              context: "Aisha just graduated with $22,000 in federal student loans. Her 6-month grace period just started, and she's not sure whether to start payments immediately or wait the full 6 months.",
              options: [
                "Wait the full 6 months and ignore the loans until forced to pay",
                "Start making payments as soon as she can afford to, even during the grace period, to reduce interest and principal sooner",
                "Take out a payday loan to pay off the student loans immediately",
                "Ask her loan servicer to cancel the debt since she just graduated",
              ],
              correctIndex: 1,
              explanation: "Making payments during the grace period, even though they're not required yet, reduces accrued interest and principal sooner, saving money over the life of the loan without any downside.",
              hint: "The grace period is optional to skip, not a reason to stop thinking about the loan.",
              xp: 15,
            },
          ],
        },
      ],
    },
  ],
};
