import type { Course } from "@/lib/types";

export const moneyBasicsCourse: Course = {
  id: "money-basics",
  title: "Money Basics",
  tagline: "Learn where your money actually goes before you're out of it.",
  description:
    "The foundational course for anyone earning a paycheck for the first time, whether it's a campus job, an internship, or financial aid refund. You'll build a real budget, learn how bank accounts and fees actually work, and figure out why your paycheck is smaller than you expected.",
  category: "Money",
  icon: "Wallet",
  color: "from-capital-400 to-capital-600",
  accent: "capital-300",
  order: 1,
  unlockLevel: 1,
  units: [
    {
      id: "money-basics-u1",
      courseId: "money-basics",
      order: 1,
      title: "Your First Budget",
      subtitle: "Where student money actually goes",
      lessons: [
        {
          id: "money-basics-u1-l1",
          unitId: "money-basics-u1",
          courseId: "money-basics",
          order: 1,
          title: "Needs vs. Wants",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Learn to sort every purchase into 'need' or 'want' before you swipe.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u1-l1-t1",
              title: "Needs keep life running",
              body: "A need is something you can't reasonably cut without a real problem: rent, groceries, textbooks required for class, your phone bill if it's how professors and employers reach you. Wants make life better but aren't required to function.",
              example:
                "Your $650/month dorm meal plan is a need. The $7 boba run after your 9am lecture is a want.",
            },
            {
              kind: "teach",
              id: "money-basics-u1-l1-t2",
              title: "The line moves depending on context",
              body: "Some things are needs in one situation and wants in another, a car is a need if it's your only way to get to a job, but a want if campus buses already get you everywhere for free.",
              analogy:
                "Think of needs as the floor of a house and wants as the furniture, you can't skip the floor, but you get to choose how much furniture fits your budget.",
            },
            {
              // Income and expense are tested in the match below but were never
              // defined; everyday words still deserve one line before the quiz.
              kind: "teach",
              id: "money-basics-u1-l1-t3",
              title: "Money in, money out",
              body: "Income is money coming in: a paycheck, a stipend, financial aid refunds, money from home. An expense is money going out: rent, food, subscriptions, that boba. Every need and every want you have is an expense. The gap between your income and your expenses is the only money you'll ever get to save or invest.",
              example:
                "A $900/month campus job is income. Rent, groceries, and Spotify are expenses. If they total $740, your gap is $160, that's what's actually available to you.",
            },
            {
              kind: "question",
              id: "money-basics-u1-l1-qm",
              type: "match",
              prompt: "Match each money term to what it means.",
              pairs: [
                { left: "Need", right: "A cost you can't skip, like rent" },
                { left: "Want", right: "A nice-to-have, like takeout" },
                { left: "Income", right: "Money coming in, like a paycheck" },
                { left: "Expense", right: "Money going out each month" },
              ],
              explanation:
                "Needs keep your life running; wants are optional. Income is money in, expenses are money out, the gap between them is what you get to save or invest.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u1-l1-q1",
              type: "mcq",
              prompt: "Which of these is most clearly a 'need' for a full-time student living off campus?",
              options: [
                "A $180 pair of limited-edition sneakers",
                "This month's $900 rent payment",
                "A premium streaming bundle with 4 services",
                "Delivery fees on weekly takeout",
              ],
              correctIndex: 1,
              explanation:
                "Rent keeps a roof over your head, miss it and you risk losing your housing, which makes it a need. The others are comfort or entertainment spending.",
              hint: "Ask: what happens if I don't pay this at all?",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l1-q2",
              type: "scenario",
              context:
                "Maya makes $800/month from her campus job. She spends $120/month on a gym membership she loves, $60/month on her phone plan, and $45/month on a subscription box she rarely opens.",
              prompt: "Which of Maya's expenses is the clearest candidate to cut if she needs to free up cash fast?",
              options: [
                "The $60 phone plan",
                "The $45 subscription box she rarely opens",
                "The $120 gym membership",
                "All three equally",
              ],
              correctIndex: 1,
              explanation:
                "A subscription she rarely uses delivers little value for the money, it's the easiest want to cut without actually losing anything she relies on.",
              hint: "Look for the expense with the lowest actual use.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l1-q3",
              type: "true-false",
              prompt: "Required textbooks for your current classes count as a 'need,' not a 'want.'",
              correctBool: true,
              explanation:
                "If a class requires the book to complete assignments or exams, it's directly tied to your ability to pass, that makes it a need, even though it still feels painful to pay for.",
              hint: "Would skipping it put your grade at risk?",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u1-l2",
          unitId: "money-basics-u1",
          courseId: "money-basics",
          order: 2,
          title: "The 50/30/20 Rule",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 30,
          summary: "Split any paycheck into needs, wants, and savings using one simple rule.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u1-l2-t1",
              title: "One rule, three buckets",
              body: "The 50/30/20 rule says: roughly 50% of your income goes to needs, 30% to wants, and 20% to savings or debt payoff. It's a starting point, not a law, you adjust the percentages to fit your real life.",
              example:
                "On an $800/month paycheck, that's about $400 for needs, $240 for wants, and $160 for savings.",
            },
            {
              kind: "teach",
              id: "money-basics-u1-l2-t2",
              title: "Students often flip the ratio",
              body: "If your school covers housing and meals through financial aid, your 'needs' bucket might shrink and you can push more into savings or wants. The percentages are a guide, not a cage.",
              analogy:
                "Think of it like a pizza cut into slices, the rule just tells you the standard slice sizes; you can still cut yours differently if your situation calls for it.",
            },
            {
              kind: "question",
              id: "money-basics-u1-l2-q1",
              type: "fill-in",
              prompt: "In the 50/30/20 rule, what percentage of income is recommended for savings and debt payoff?",
              accept: ["20", "20%"],
              explanation:
                "The last chunk, 20%, is aimed at savings, an emergency fund, or paying down debt, the part of the budget that builds your future instead of covering today.",
              hint: "It's the smallest of the three buckets.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l2-q2",
              type: "scenario",
              context:
                "Jordan earns $800/month from a part-time café job. Using the 50/30/20 rule, he wants to know his target 'wants' spending for the month.",
              prompt: "About how much should Jordan budget for wants under the 50/30/20 rule?",
              options: ["$80", "$160", "$240", "$400"],
              correctIndex: 2,
              explanation:
                "30% of $800 is $240. That's the target ceiling for fun spending like eating out, entertainment, and non-essential purchases.",
              hint: "30% of $800, move the decimal, then multiply by 3.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l2-q3",
              type: "mcq",
              prompt: "Why is the 50/30/20 rule useful even though it's not exact?",
              options: [
                "It guarantees you'll never overspend",
                "It gives you a simple starting split you can adjust to your situation",
                "It's required by most banks",
                "It only works for people earning over $50,000/year",
              ],
              correctIndex: 1,
              explanation:
                "Its value is simplicity, a rough three-way split is easier to actually follow than a complicated spreadsheet, and you can tune it as your income or expenses change.",
              hint: "Think about why simple rules of thumb get used at all.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u1-l3",
          unitId: "money-basics-u1",
          courseId: "money-basics",
          order: 3,
          title: "Tracking What You Actually Spend",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 30,
          summary: "Most budgets fail from not knowing real spending. Here's how to catch it.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u1-l3-t1",
              title: "You can't fix what you don't track",
              body: "Most people underestimate how much they spend on small, frequent purchases like coffee, delivery fees, and app subscriptions. Tracking every transaction for even one week reveals patterns a mental estimate always misses.",
              example:
                "A $6 coffee every weekday adds up to about $120 a month, roughly the same as a phone bill, but it rarely gets budgeted for.",
            },
            {
              kind: "teach",
              id: "money-basics-u1-l3-t2",
              title: "Small recurring charges are budget killers",
              body: "A single $12.99 subscription looks harmless. Three or four of them, plus a couple you forgot you signed up for, can quietly eat $50+ a month with zero conscious decision-making.",
              analogy:
                "It's death by a thousand cuts, no single charge hurts, but the total can bleed a budget dry.",
            },
            {
              kind: "question",
              id: "money-basics-u1-l3-q1",
              type: "scenario",
              context:
                "Priya checks her bank app and finds she's paying for three streaming services ($15.99, $9.99, and $6.99) plus a $4.99 cloud storage plan she forgot about, totaling about $38/month.",
              prompt: "What's the most useful first step for Priya to fix this?",
              options: [
                "Cancel her phone plan instead",
                "Review each subscription and cancel the ones she doesn't actively use",
                "Switch banks",
                "Ignore it since it's under $50",
              ],
              correctIndex: 1,
              explanation:
                "Once forgotten subscriptions are visible, the fastest fix is auditing them directly, keep what you use, cancel what you don't. That's real money recovered with zero lifestyle change.",
              hint: "The problem is specific subscriptions, so the fix should target them directly.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l3-q2",
              type: "true-false",
              prompt: "Tracking your spending for just one week can reveal spending patterns you weren't aware of.",
              correctBool: true,
              explanation:
                "Even a short tracking window tends to surface habits, like daily small purchases, that don't stand out individually but add up fast.",
              hint: "Think about how visible daily habits become once written down.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l3-q3",
              type: "fill-in",
              prompt: "Fill in the blank: recurring charges you forgot about, like unused streaming apps, are often called 'zombie ___.'",
              accept: ["subscriptions", "subscription"],
              explanation:
                "'Zombie subscriptions' are recurring charges that keep billing you long after you stopped using the service, they're a top hidden budget leak.",
              hint: "It's a recurring monthly charge.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u1-l3-q4",
              type: "mcq",
              prompt: "A daily $6 coffee habit on weekdays costs roughly how much per month?",
              options: ["$30", "$60", "$120", "$200"],
              correctIndex: 2,
              explanation:
                "About 20 weekdays a month × $6 = roughly $120/month, a habit that feels small daily but adds up to a real budget line.",
              hint: "Estimate about 20 weekdays in a month.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u1-l4",
          unitId: "money-basics-u1",
          courseId: "money-basics",
          order: 4,
          title: "Unit 1 Challenge: Build a Budget",
          difficulty: "Beginner",
          kind: "challenge",
          xp: 75,
          summary: "Prove you can sort spending, apply the 50/30/20 rule, and spot budget leaks.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u1-l4-t1",
              title: "Quick recap",
              body: "You've learned to separate needs from wants, split income with the 50/30/20 rule, and track spending to catch leaks like zombie subscriptions. This challenge mixes all three.",
            },
            {
              kind: "question",
              id: "money-basics-u1-l4-q1",
              type: "scenario",
              context:
                "Diego earns $1,000/month between a work-study job and a small scholarship stipend. His rent share is $500, his phone bill is $50, and he spends about $150/month on eating out and entertainment.",
              prompt: "Applying the 50/30/20 rule, is Diego over or under his target 'needs' spending?",
              options: [
                "Over, needs should be about $500, and his needs total $550",
                "Right on target, his needs are exactly 50%",
                "Under, his needs are well below 50%",
                "There's not enough information to tell",
              ],
              correctIndex: 0,
              explanation:
                "50% of $1,000 is $500. Rent ($500) plus his phone bill ($50) totals $550 in needs, $50 over the 50% target, showing how real needs can run a bit hot even for a careful budgeter.",
              hint: "Calculate 50% of his total income, then add up his needs.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u1-l4-q2",
              type: "mcq",
              prompt: "Which spending category should you generally review FIRST when trying to free up cash quickly?",
              options: [
                "Rent or housing payments",
                "Required textbooks",
                "Unused subscriptions and low-value wants",
                "Tuition",
              ],
              correctIndex: 2,
              explanation:
                "Needs like rent and tuition are hard to cut without real consequences, but unused subscriptions and low-value wants can usually be trimmed with no downside.",
              hint: "Which category has the least attached consequence if cut?",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u1-l4-q3",
              type: "true-false",
              prompt: "The 50/30/20 rule is a fixed law that every student's budget must follow exactly.",
              correctBool: false,
              explanation:
                "It's a flexible guideline. Financial aid, campus housing, and family support can all shift the right percentages for a given student.",
              hint: "Recall how the rule flexes based on your situation.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u1-l4-q4",
              type: "fill-in",
              prompt: "What term describes an expense that is not required but improves quality of life, like streaming or eating out?",
              accept: ["want", "wants"],
              explanation:
                "A 'want' adds enjoyment or convenience but isn't required to function, the opposite of a 'need.'",
              hint: "It's the opposite of a need.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u1-l4-q5",
              type: "scenario",
              context:
                "Emma tracks her spending for a week and discovers $22 in delivery fees, a forgotten $14.99 app subscription, and $40 in impulse snack purchases, about $77 total she hadn't accounted for.",
              prompt: "What's the biggest lesson from Emma's tracking exercise?",
              options: [
                "She should stop eating entirely",
                "Small untracked purchases can add up to a significant hidden cost",
                "Tracking spending is a waste of time",
                "She needs a higher-paying job before budgeting matters",
              ],
              correctIndex: 1,
              explanation:
                "Emma's $77 in 'invisible' spending shows exactly why tracking matters, small purchases are easy to underestimate until they're written down and totaled.",
              hint: "Focus on what the tracking revealed, not the specific dollar amounts.",
              xp: 15,
            },
          ],
        },
      ],
    },
    {
      id: "money-basics-u2",
      courseId: "money-basics",
      order: 2,
      title: "Banking & Cash Flow",
      subtitle: "Accounts, fees, and your first emergency fund",
      lessons: [
        {
          id: "money-basics-u2-l1",
          unitId: "money-basics-u2",
          courseId: "money-basics",
          order: 1,
          title: "Checking vs. Savings",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 25,
          summary: "Understand what each account type is actually built for.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u2-l1-t1",
              title: "Two accounts, two jobs",
              body: "A checking account is for money you spend often, rent, groceries, debit card swipes. A savings account is for money you're setting aside and not touching, and it usually earns you a bit of interest for leaving it alone.",
              example:
                "Your $800 paycheck lands in checking to cover the month's bills; the $50 you don't need this month moves to savings.",
            },
            {
              kind: "teach",
              id: "money-basics-u2-l1-t2",
              title: "Savings accounts limit frequent withdrawals",
              body: "Many savings accounts aren't built for constant access, some banks still cap or discourage frequent transfers out. That friction is actually useful: it nudges you not to dip into savings for everyday spending.",
              analogy:
                "Checking is your wallet; savings is the box under your bed you don't open every day.",
            },
            {
              kind: "question",
              id: "money-basics-u2-l1-q1",
              type: "mcq",
              prompt: "Which account should you use for your debit card and everyday purchases?",
              options: ["Savings account", "Checking account", "Either, it doesn't matter", "Neither, use cash only"],
              correctIndex: 1,
              explanation:
                "Checking accounts are designed for frequent, everyday transactions, that's exactly what a debit card linked to it is for.",
              hint: "Which account is meant for money you access constantly?",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l1-q2",
              type: "true-false",
              prompt: "Savings accounts are generally meant for money you plan to leave alone, not for daily spending.",
              correctBool: true,
              explanation:
                "Savings accounts are structured to hold money you're not actively spending, which is also why they tend to pay you interest for keeping it there.",
              hint: "Think about which account earns interest and why.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l1-q3",
              type: "scenario",
              context:
                "Tyler gets a $400 refund check from financial aid. He knows he won't need most of it for at least two months, but he might need $50 of it for a textbook next week.",
              prompt: "What's the smartest way for Tyler to split this money?",
              options: [
                "Put all $400 in savings and never touch it",
                "Keep all $400 in checking in case something comes up",
                "Keep $50 in checking for the textbook and move $350 to savings",
                "Spend it all before he's tempted to lose it",
              ],
              correctIndex: 2,
              explanation:
                "Keeping only what he needs soon in checking, and moving the rest to savings, keeps his near-term cash accessible while the rest sits somewhere it won't get casually spent.",
              hint: "Match each portion of the money to how soon he'll need it.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u2-l2",
          unitId: "money-basics-u2",
          courseId: "money-basics",
          order: 2,
          title: "Bank Fees & Overdrafts",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 35,
          summary: "See how a $4 coffee can turn into a $39 mistake.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u2-l2-t1",
              title: "Overdraft fees punish small mistakes hard",
              body: "An overdraft happens when you spend more than what's in your account and the bank covers it anyway, for a fee. That fee is often $30-$35 flat, no matter how small the purchase that triggered it was.",
              example:
                "You have $2 left in checking and buy a $4 coffee. The bank covers the $2 gap and charges you a $35 overdraft fee, a $4 coffee just cost $39.",
            },
            {
              kind: "teach",
              id: "money-basics-u2-l2-t2",
              title: "You can usually opt out of overdraft coverage",
              body: "Many banks let you decline 'overdraft protection' for debit purchases, the card just gets declined instead of approved with a fee. For most students, a declined card is far better than a surprise $35 charge.",
              analogy:
                "It's the difference between a door that locks when you're out of key cards versus one that lets you in but bills you $35 for the inconvenience.",
            },
            {
              kind: "question",
              id: "money-basics-u2-l2-q1",
              type: "scenario",
              context:
                "Sam's checking account has $3.50 left. He buys a $4.25 sandwich with his debit card and his bank approves it under overdraft coverage, charging a standard $35 fee.",
              prompt: "How much did that sandwich effectively cost Sam?",
              options: ["$4.25", "$35.00", "$39.25", "$3.50"],
              correctIndex: 2,
              explanation:
                "The $4.25 purchase plus the $35 overdraft fee totals $39.25, a small purchase turned very expensive because his account balance was too low to cover it.",
              hint: "Add the purchase price to the overdraft fee.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l2-q2",
              type: "fill-in",
              prompt: "What is it called when your bank covers a purchase that exceeds your balance and charges you a fee for it?",
              accept: ["overdraft", "an overdraft", "overdraft fee"],
              explanation:
                "That's an overdraft, the bank pays the difference so your purchase goes through, then charges you a fee (often $30-$35) for the service.",
              hint: "It starts with 'over.'",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l2-q3",
              type: "true-false",
              prompt: "Most banks require you to accept overdraft coverage, there's no way to have a purchase simply declined instead.",
              correctBool: false,
              explanation:
                "You can typically opt out of overdraft coverage for debit card purchases, so instead of an approved purchase plus a fee, the card is just declined.",
              hint: "Think about whether banks are required to auto-approve every purchase.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l2-q4",
              type: "mcq",
              prompt: "What's the best habit to avoid overdraft fees altogether?",
              options: [
                "Never check your account balance",
                "Keep a small buffer in checking and check your balance before big purchases",
                "Only use credit cards, never debit",
                "Close your checking account",
              ],
              correctIndex: 1,
              explanation:
                "A small cash buffer plus the habit of glancing at your balance before spending catches most overdraft situations before they happen.",
              hint: "Prevention beats opting out after the fact.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u2-l3",
          unitId: "money-basics-u2",
          courseId: "money-basics",
          order: 3,
          title: "High-Yield Savings & Your First Emergency Fund",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 35,
          summary: "Make your idle cash earn something, and start a $500 safety net.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u2-l3-t1",
              title: "APY is what your money earns for sitting still",
              body: "APY (Annual Percentage Yield) is the rate a savings account pays you per year. A typical big-bank savings account might pay 0.01% APY, while online high-yield savings accounts often pay around 4% APY or more.",
              example:
                "On $1,000 saved for a year: 0.01% APY earns you about $0.10. 4% APY earns you about $40, for doing nothing differently except choosing a better account.",
            },
            {
              kind: "teach",
              id: "money-basics-u2-l3-t2",
              title: "Start small: the $500 emergency fund",
              body: "An emergency fund is cash set aside only for real emergencies, a car repair, a medical bill, a broken laptop you need for class. $500 is a realistic first goal that covers most small-scale student emergencies.",
              analogy:
                "Think of it as a shock absorber, it doesn't stop bumps in the road, but it keeps them from wrecking your whole budget.",
            },
            {
              kind: "question",
              id: "money-basics-u2-l3-q1",
              type: "mcq",
              prompt: "Roughly how much more would $1,000 earn in a year at 4% APY compared to 0.01% APY?",
              options: ["About $0.40 more", "About $4 more", "About $40 more", "About $400 more"],
              correctIndex: 2,
              explanation:
                "4% of $1,000 is about $40/year, versus $0.10/year at 0.01%, a difference of roughly $40 for simply choosing a higher-yield account.",
              hint: "Calculate 4% of $1,000 versus 0.01% of $1,000.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l3-q2",
              type: "fill-in",
              prompt: "What acronym describes the yearly interest rate a savings account pays you?",
              accept: ["apy"],
              explanation:
                "APY stands for Annual Percentage Yield, the rate that determines how much your saved money grows over a year.",
              hint: "Three letters, starts with 'A' for Annual.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l3-q3",
              type: "scenario",
              context:
                "Aaliyah's laptop charger breaks right before finals and a replacement costs $89. She has $500 sitting in a savings account she's been calling her emergency fund.",
              prompt: "Is using $89 from her emergency fund for this a reasonable use of it?",
              options: [
                "No, only medical bills count as emergencies",
                "Yes, an unexpected necessary expense for schoolwork is a reasonable emergency fund use",
                "No, she should put it on a credit card instead no matter what",
                "It doesn't matter, emergency funds are just for looks",
              ],
              correctIndex: 1,
              explanation:
                "An emergency fund exists for unplanned, necessary costs, a charger she needs to finish finals qualifies, even though it's smaller than a medical bill.",
              hint: "Ask whether the expense was both unexpected and necessary.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u2-l3-q4",
              type: "true-false",
              prompt: "$500 is a commonly recommended first emergency fund goal for students, even before building a larger fund.",
              correctBool: true,
              explanation:
                "$500 is a realistic starter target that covers many common small emergencies, and hitting it builds the habit before working toward a larger cushion.",
              hint: "Recall the specific dollar figure discussed as a first milestone.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u2-l4",
          unitId: "money-basics-u2",
          courseId: "money-basics",
          order: 4,
          title: "Unit 2 Challenge: Banking Smarter",
          difficulty: "Intermediate",
          kind: "challenge",
          xp: 85,
          summary: "Test your knowledge of accounts, fees, APY, and emergency funds together.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u2-l4-t1",
              title: "Quick recap",
              body: "You've covered checking vs. savings, how overdraft fees can turn a $4 coffee into a $39 charge, and how APY plus an emergency fund put your idle cash to work. Let's mix it all together.",
            },
            {
              kind: "question",
              id: "money-basics-u2-l4-q1",
              type: "scenario",
              context:
                "Malik has $6 in checking and his phone bill of $50 is about to auto-pay. If it goes through, he'll be $44 short, and his bank charges a $35 overdraft fee per transaction.",
              prompt: "What's Malik's smartest move right now?",
              options: [
                "Do nothing and let the overdraft happen",
                "Transfer money into checking before the bill hits, or contact the biller to delay it",
                "Close his checking account",
                "Cancel his phone service permanently",
              ],
              correctIndex: 1,
              explanation:
                "Acting before the auto-payment hits, by transferring in funds or delaying the charge, avoids turning a $44 shortfall into a $79 problem with the overdraft fee added.",
              hint: "The key is acting before the automatic payment processes.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u2-l4-q2",
              type: "mcq",
              prompt: "Why would someone choose a high-yield savings account over a traditional big-bank savings account?",
              options: [
                "It's required by law",
                "It typically earns a much higher APY on the same balance",
                "It has no minimum balance ever, in every case",
                "It allows unlimited free overdrafts",
              ],
              correctIndex: 1,
              explanation:
                "The main advantage is APY, high-yield accounts often pay around 4% versus 0.01% at many traditional banks, meaning the same balance earns far more over time.",
              hint: "Think about the interest rate comparison you just learned.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u2-l4-q3",
              type: "true-false",
              prompt: "An emergency fund should typically be kept in the same account you use for everyday debit card spending.",
              correctBool: false,
              explanation:
                "Keeping it separate, often in a savings account, adds a small amount of friction that helps prevent you from accidentally spending it on non-emergencies.",
              hint: "Recall the reasoning behind keeping spending and savings separate.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u2-l4-q4",
              type: "fill-in",
              prompt: "What dollar amount was used as a realistic first emergency fund goal?",
              accept: ["500", "$500"],
              explanation:
                "$500 is a commonly cited first milestone, big enough to cover many real emergencies, small enough to feel achievable.",
              hint: "It's a round number in the hundreds.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u2-l4-q5",
              type: "scenario",
              context:
                "Reyna keeps $1,200 in a checking account earning 0.01% APY because she says it's 'easier to just leave it there.' She doesn't expect to need most of it for at least six months.",
              prompt: "What's the best advice for Reyna based on what you've learned?",
              options: [
                "Leave it exactly where it is, it doesn't matter",
                "Spend it all now before it loses value",
                "Move the portion she won't need soon into a high-yield savings account to earn more",
                "Withdraw it as cash and keep it under her mattress",
              ],
              correctIndex: 2,
              explanation:
                "Since she won't need most of it for six months, moving it to a high-yield account (around 4% APY) instead of a near-zero-interest checking account earns meaningfully more with no added risk to her spending needs.",
              hint: "Match the money to an account that fits how soon she needs it, and consider APY.",
              xp: 15,
            },
          ],
        },
      ],
    },
    {
      id: "money-basics-u3",
      courseId: "money-basics",
      order: 3,
      title: "Taxes & Paychecks",
      subtitle: "Why your paycheck is smaller than you think",
      lessons: [
        {
          id: "money-basics-u3-l1",
          unitId: "money-basics-u3",
          courseId: "money-basics",
          order: 1,
          title: "Gross Pay vs. Net Pay",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 30,
          summary: "Find out why a $15/hr job doesn't actually pay you $15/hr.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u3-l1-t1",
              title: "Gross pay is the sticker price",
              body: "Gross pay is your total earnings before anything is taken out, the number in your offer letter. Net pay (also called take-home pay) is what actually lands in your bank account after taxes and other deductions.",
              example:
                "At $15/hr for 20 hours a week, gross pay is $300/week. After taxes, net pay might land closer to $255-$270/week depending on where you live.",
            },
            {
              kind: "teach",
              id: "money-basics-u3-l1-t2",
              title: "The gap is mostly taxes",
              body: "Federal income tax, state income tax (in most states), and FICA taxes all get taken out of every paycheck automatically, before you ever see the money.",
              analogy:
                "Gross pay is like the sticker price on a car, net pay is what you actually drive away paying after fees and taxes are added on top.",
            },
            {
              kind: "question",
              id: "money-basics-u3-l1-q1",
              type: "mcq",
              prompt: "What's the key difference between gross pay and net pay?",
              options: [
                "Gross pay is monthly, net pay is weekly",
                "Gross pay is before deductions, net pay is what you actually take home",
                "They're two names for the same thing",
                "Net pay is always higher than gross pay",
              ],
              correctIndex: 1,
              explanation:
                "Gross pay is your full earnings before anything is withheld; net pay is what's left after taxes and other deductions come out, and net pay is always the smaller number.",
              hint: "Think about which number appears in your offer letter versus your bank deposit.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l1-q2",
              type: "scenario",
              context:
                "Chris works 15 hours a week at $16/hr, making $240/week in gross pay. After taxes are withheld, his direct deposit shows $205.",
              prompt: "What does the $35 difference between $240 and $205 represent?",
              options: [
                "A bank fee",
                "Taxes and other paycheck deductions",
                "A mistake his employer needs to fix",
                "Tips he forgot to count",
              ],
              correctIndex: 1,
              explanation:
                "That gap is the normal result of taxes (and possibly other deductions) being withheld from gross pay, it's expected, not an error.",
              hint: "Recall what typically separates gross pay from net pay.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l1-q3",
              type: "true-false",
              prompt: "The hourly rate listed in a job offer (like $15/hr) is what you'll actually receive per hour in your bank account.",
              correctBool: false,
              explanation:
                "That listed rate is gross pay. Your actual take-home per hour is lower once taxes and deductions are withheld.",
              hint: "Distinguish between the advertised rate and the deposited amount.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u3-l2",
          unitId: "money-basics-u3",
          courseId: "money-basics",
          order: 2,
          title: "W-4, W-2, and FICA",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Decode the tax paperwork every job hands you.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u3-l2-t1",
              title: "W-4 vs. W-2: before and after",
              body: "A W-4 is a form you fill out when you START a job, it tells your employer how much tax to withhold from each paycheck. A W-2 is a form your employer sends you AFTER the year ends, summarizing everything you were paid and withheld.",
              example:
                "You fill out a W-4 on day one at the campus bookstore. The following January, that job sends you a W-2 to use for filing your taxes.",
            },
            {
              kind: "teach",
              id: "money-basics-u3-l2-t2",
              title: "FICA funds Social Security and Medicare",
              body: "FICA is a payroll tax split into two parts: Social Security (6.2% of pay) and Medicare (1.45% of pay), totaling 7.65%. It's withheld automatically from every paycheck, no matter your income level or age.",
              analogy:
                "FICA is like a mandatory subscription everyone with a paycheck pays into, it funds benefits you (or your family) may draw on decades from now.",
            },
            {
              kind: "question",
              id: "money-basics-u3-l2-q1",
              type: "fill-in",
              prompt: "Which form do you fill out when you START a new job to set your tax withholding?",
              accept: ["w-4", "w4"],
              explanation:
                "The W-4 tells your new employer how much tax to withhold from each paycheck, it's completed at the start of a job, not the end.",
              hint: "It's a W-form with a single digit.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l2-q2",
              type: "mcq",
              prompt: "What does FICA tax fund?",
              options: [
                "Your employer's health insurance plan",
                "Social Security and Medicare",
                "Your state's road maintenance",
                "Your college tuition",
              ],
              correctIndex: 1,
              explanation:
                "FICA is split between Social Security (6.2%) and Medicare (1.45%), together 7.65% of your pay, withheld automatically from every paycheck.",
              hint: "The acronym is tied to federal insurance programs.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l2-q3",
              type: "true-false",
              prompt: "A W-2 is something you receive after a year of work, summarizing your pay and withholding for tax filing.",
              correctBool: true,
              explanation:
                "Employers send W-2s after the calendar year ends, and you use that form to file your taxes for that year.",
              hint: "Think about the timing: is this filled out at the start or received at the end?",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l2-q4",
              type: "scenario",
              context:
                "Nia starts a new internship in June and fills out paperwork on her first day, including a form that tells her employer how much federal tax to withhold from each check.",
              prompt: "Which form is Nia most likely filling out?",
              options: ["A W-2", "A W-4", "A FICA form", "A 1099"],
              correctIndex: 1,
              explanation:
                "Setting withholding amounts at the start of a job is exactly what the W-4 is for, the W-2 comes later, summarizing the year's actual pay.",
              hint: "Recall which form is completed at the start of employment.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u3-l3",
          unitId: "money-basics-u3",
          courseId: "money-basics",
          order: 3,
          title: "Do Students Need to File Taxes?",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Understand refunds and education credits like the AOTC at a high level.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u3-l3-t1",
              title: "Yes, most working students should file",
              body: "If taxes were withheld from your paycheck, filing a tax return is usually how you find out if you overpaid and get that money back as a refund. Many part-time student workers have too much withheld and are owed money back.",
              example:
                "If $600 in federal tax was withheld from your part-time job over the year but you only actually owed $350, filing gets you a $250 refund.",
            },
            {
              kind: "teach",
              id: "money-basics-u3-l3-t2",
              title: "Education credits can reduce what you owe",
              body: "The American Opportunity Tax Credit (AOTC) is a credit that can reduce taxes owed for eligible students paying for tuition and required course materials, up to a set yearly limit. It's filed as part of a tax return, generally by whoever claims the student or by the student themselves if independent.",
              analogy:
                "A tax credit works like a coupon applied directly to what you owe, rather than just lowering the amount your income gets taxed on.",
            },
            {
              kind: "question",
              id: "money-basics-u3-l3-q1",
              type: "true-false",
              prompt: "If you had taxes withheld from a part-time job, filing a tax return is generally how you'd find out if you're owed a refund.",
              correctBool: true,
              explanation:
                "Filing compares what was withheld against what you actually owed, if you overpaid throughout the year, filing is what triggers your refund.",
              hint: "Think about how you'd learn whether you overpaid.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l3-q2",
              type: "fill-in",
              prompt: "What's the common acronym for the education tax credit that helps offset tuition and course material costs?",
              accept: ["aotc"],
              explanation:
                "AOTC stands for American Opportunity Tax Credit, a credit aimed at reducing the tax burden for eligible students' education costs.",
              hint: "Four letters, related to education 'opportunity.'",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l3-q3",
              type: "scenario",
              context:
                "Owen worked a part-time campus job all year and had $480 in federal taxes withheld from his paychecks. When he files, he learns he actually only owed $310 in federal tax for the year.",
              prompt: "What should Owen expect after filing?",
              options: [
                "He owes an additional $170",
                "He gets a refund of about $170",
                "Nothing changes since withholding is final",
                "He must pay a penalty for overpaying",
              ],
              correctIndex: 1,
              explanation:
                "Since he had $480 withheld but only owed $310, filing gets him the $170 difference back as a refund, that's the whole point of reconciling withholding against actual tax owed.",
              hint: "Subtract what he owed from what was withheld.",
              xp: 10,
            },
            {
              kind: "question",
              id: "money-basics-u3-l3-q4",
              type: "mcq",
              prompt: "What is a tax credit like the AOTC generally used for, at a high level?",
              options: [
                "Increasing your gross pay",
                "Reducing the amount of tax you owe, often tied to eligible education expenses",
                "Replacing the need to file a return",
                "Avoiding FICA taxes entirely",
              ],
              correctIndex: 1,
              explanation:
                "Education credits like the AOTC reduce the tax you owe based on qualifying expenses such as tuition and required course materials, they don't touch gross pay or FICA.",
              hint: "Think about what a 'credit' does to your tax bill versus your paycheck.",
              xp: 10,
            },
          ],
        },
        {
          id: "money-basics-u3-l4",
          unitId: "money-basics-u3",
          courseId: "money-basics",
          order: 4,
          title: "Unit 3 Challenge: Paychecks & Taxes",
          difficulty: "Advanced",
          kind: "challenge",
          xp: 95,
          summary: "Pull together gross vs. net pay, W-4/W-2, FICA, and filing basics.",
          cards: [
            {
              kind: "teach",
              id: "money-basics-u3-l4-t1",
              title: "Quick recap",
              body: "You now know why gross pay isn't what hits your account, what the W-4 and W-2 are each for, what FICA funds, and why filing a return can get you money back. Time to combine it all.",
            },
            {
              kind: "question",
              id: "money-basics-u3-l4-q1",
              type: "scenario",
              context:
                "Layla earns $18/hr and works 12 hours a week, for gross pay of $216/week. Her pay stub shows federal tax, state tax, and FICA (7.65%) all withheld, leaving her with $182 in net pay.",
              prompt: "What does the roughly $34 gap between Layla's gross and net pay represent?",
              options: [
                "A bank overdraft fee",
                "Combined federal tax, state tax, and FICA withholding",
                "Money her employer is keeping as profit",
                "A mistake on her pay stub",
              ],
              correctIndex: 1,
              explanation:
                "That gap is the normal combination of federal income tax, state income tax, and the 7.65% FICA tax, all withheld automatically before she's paid.",
              hint: "Recall the three main types of paycheck withholding.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u3-l4-q2",
              type: "mcq",
              prompt: "Which statement correctly distinguishes the W-4 from the W-2?",
              options: [
                "The W-4 is filed at the start of a job to set withholding; the W-2 summarizes a year's pay afterward",
                "The W-2 is filed at the start of a job; the W-4 comes afterward",
                "They are the exact same form used interchangeably",
                "Only the W-2 affects how much tax is withheld from each check",
              ],
              correctIndex: 0,
              explanation:
                "The W-4 (filled out when starting a job) sets your withholding going forward; the W-2 (received after the year ends) reports what was actually paid and withheld.",
              hint: "Match each form to a point in time: starting a job versus after the year ends.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u3-l4-q3",
              type: "fill-in",
              prompt: "What combined percentage of your pay does FICA (Social Security + Medicare) typically take?",
              accept: ["7.65", "7.65%"],
              explanation:
                "6.2% for Social Security plus 1.45% for Medicare equals 7.65% total FICA withholding on most paychecks.",
              hint: "Add 6.2% and 1.45%.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u3-l4-q4",
              type: "true-false",
              prompt: "A student who had taxes withheld from a part-time job should generally consider filing a tax return to check for a possible refund.",
              correctBool: true,
              explanation:
                "Filing is how withheld taxes get reconciled against what's actually owed, many part-time student workers are owed a refund and only get it by filing.",
              hint: "Recall the Owen scenario from the previous lesson.",
              xp: 15,
            },
            {
              kind: "question",
              id: "money-basics-u3-l4-q5",
              type: "scenario",
              context:
                "Devon is comparing two summer internship offers: one lists a $17/hr gross rate, the other lists a $17/hr rate but explicitly says it's 'take-home pay guaranteed.'",
              prompt: "Based on what you've learned about gross vs. net pay, what should Devon expect?",
              options: [
                "Both offers pay the exact same amount per hour in his bank account",
                "The 'take-home pay guaranteed' offer would put more actual cash in his account per hour worked, since the first $17/hr gets reduced by taxes before it's deposited",
                "Gross pay is always higher than take-home pay guarantees",
                "There's no meaningful difference between the two phrasings",
              ],
              correctIndex: 1,
              explanation:
                "A standard '$17/hr' offer is gross pay, which shrinks after taxes are withheld. A 'take-home pay guaranteed' offer at the same rate means Devon would actually receive $17/hr after deductions, which is a better deal in real dollars.",
              hint: "Remember that a plain hourly rate usually refers to gross pay, not what lands in the bank.",
              xp: 15,
            },
          ],
        },
      ],
    },
  ],
};
