import type { Course } from "@/lib/types";

export const realEstateCourse: Course = {
  id: "real-estate",
  title: "Real Estate",
  tagline: "From signing your first lease to owning property that pays you back.",
  description:
    "Real estate is the asset most students touch before they ever buy a stock, you're renting something right now. This course walks you from surviving a lease and getting your deposit back, through how mortgages actually work, to using property as an investment, house hack, or REIT position.",
  category: "Investing",
  icon: "Building2",
  color: "from-emerald-400 to-teal-500",
  accent: "emerald-300",
  order: 4,
  unlockLevel: 3,
  units: [
    // ────────────────────────────────────────────────────────────────
    // UNIT 1: Rent Like You Mean It
    // ────────────────────────────────────────────────────────────────
    {
      id: "real-estate-u1",
      courseId: "real-estate",
      order: 1,
      title: "Rent Like You Mean It",
      subtitle: "Leases, deposits, insurance, and rent math for your first place off campus",
      lessons: [
        {
          id: "real-estate-u1-l1",
          unitId: "real-estate-u1",
          courseId: "real-estate",
          order: 1,
          title: "How a Lease Actually Works",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "What you're really signing when you sign a 12-month lease with roommates.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u1-l1-t1",
              title: "A lease is a contract, not a formality",
              body: "A standard lease locks you into paying rent for a fixed term, usually 12 months, even if you move out early, transfer schools, or hate your roommates by month three. Breaking it early can cost you the remaining rent, a penalty fee, or both.",
              example: "You sign a 12-month lease starting August 1. In November you decide to study abroad. Unless your lease has a subletting or early-termination clause, you may still owe rent through July.",
            },
            {
              kind: "teach",
              id: "real-estate-u1-l1-t2",
              title: "Joint and several liability",
              body: "When four roommates sign one lease, most leases make each person 'jointly and severally liable', meaning the landlord can legally collect the FULL rent from any single roommate if the others don't pay, not just their 1/4 share.",
              analogy: "It's like four people cosigning one giant IOU: if three of them vanish, the landlord can knock on the door of whoever's left and demand the whole amount.",
            },
            {
              kind: "question",
              id: "real-estate-u1-l1-q1",
              type: "true-false",
              prompt: "If your roommate stops paying their share of rent, the landlord can only come after that roommate, not you.",
              correctBool: false,
              explanation: "Under joint and several liability (standard in most roommate leases), the landlord can legally pursue any signer for the full rent amount, you'd then have to try to collect from your roommate yourself.",
              hint: "Think about what 'joint and several' means for a group of signers.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l1-q2",
              type: "mcq",
              prompt: "You want to move out 4 months into a 12-month lease. What's the SAFEST way to do it without owing rent for the remaining 8 months?",
              options: [
                "Just stop paying and move out",
                "Ask the landlord about a formal sublease or lease-release clause in writing",
                "Tell your roommates verbally and hope it works out",
                "Change the locks so the landlord can't find you",
              ],
              correctIndex: 1,
              explanation: "Getting a written sublease agreement or lease-release from the landlord protects you legally, verbal promises and just leaving both still leave you on the hook for rent.",
              hint: "Anything not in writing is hard to enforce later.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l1-q3",
              type: "scenario",
              context: "You and 3 friends sign a 12-month lease at $2,800/month. Two months in, one roommate drops out of school and stops paying their $700 share.",
              prompt: "What is the landlord most likely legally entitled to do?",
              options: [
                "Nothing, they can only bill the roommate who left",
                "Reduce the total rent to $2,100 since one person left",
                "Demand the full $2,800 from any remaining roommate(s) each month",
                "Evict all four roommates immediately with no notice",
              ],
              correctIndex: 2,
              explanation: "With joint and several liability, the landlord isn't obligated to split the loss, they can pursue any remaining signer(s) for the full monthly rent, leaving the roommates to sort out reimbursement among themselves.",
              hint: "Rent doesn't shrink just because a roommate leaves.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u1-l2",
          unitId: "real-estate-u1",
          courseId: "real-estate",
          order: 2,
          title: "Getting Your Deposit Back",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Document everything, it's the difference between a $1,000 refund and a $1,000 fight.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u1-l2-t1",
              title: "Normal wear vs. damage",
              body: "Landlords can only deduct from your security deposit for actual damage beyond 'normal wear and tear', faded paint or worn carpet from regular living doesn't count, but a wine stain on the carpet or a hole in the wall does.",
              example: "Small nail holes from hanging a poster: normal wear. A cracked window from a party: damage you'll likely pay for.",
            },
            {
              kind: "teach",
              id: "real-estate-u1-l2-t2",
              title: "Photograph everything, move-in and move-out",
              body: "Timestamped photos (or a video walkthrough) of every room on move-in day are your proof that pre-existing scuffs weren't caused by you, take the same photos again on move-out day.",
              analogy: "Think of it like taking a 'before' picture before a haircut, without it, nobody can prove what actually changed.",
            },
            {
              kind: "question",
              id: "real-estate-u1-l2-q1",
              type: "fill-in",
              prompt: "Fill in the blank: Landlords can deduct for damage, but not for normal wear and ___.",
              accept: ["tear", "wear and tear"],
              explanation: "\"Normal wear and tear\" is the legal standard, everyday use like light carpet wear or small scuffs generally can't be charged to your deposit.",
              hint: "It's a common two-word legal phrase.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l2-q2",
              type: "mcq",
              prompt: "What's the single best habit for protecting your security deposit when you move in?",
              options: [
                "Trust the landlord's word about the unit's condition",
                "Take dated photos/video of every room before you move anything in",
                "Wait until move-out to check for existing damage",
                "Only worry about it if something looks obviously broken",
              ],
              correctIndex: 1,
              explanation: "Photo or video evidence from move-in day is the clearest way to prove which damage already existed versus what happened during your lease.",
              hint: "Evidence beats memory in a deposit dispute.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l2-q3",
              type: "scenario",
              context: "You move out of a $2,000/month apartment after 12 months. Your landlord withholds your full $2,000 deposit, citing 'general cleaning and wear.'",
              prompt: "What should you do first?",
              options: [
                "Accept it, landlords always have the final say",
                "Request an itemized list of deductions in writing, then compare it to your move-in photos",
                "Stop paying rent at your next place out of spite",
                "Assume it's not worth fighting over",
              ],
              correctIndex: 1,
              explanation: "Most states require landlords to provide an itemized list of deductions. Comparing it against your move-in documentation is how you'd challenge unfair charges, including in small claims court if needed.",
              hint: "You have a legal right to an explanation of every deduction.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u1-l3",
          unitId: "real-estate-u1",
          courseId: "real-estate",
          order: 3,
          title: "Renters Insurance & Rent Math",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 30,
          summary: "A $15/month policy and the 30% rule that keeps rent from eating your budget.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u1-l3-t1",
              title: "Renters insurance is cheap protection",
              body: "For roughly $15, $25 a month, renters insurance covers your personal belongings (laptop, furniture, clothes) if they're stolen or damaged by fire, water, or a break-in, and it can cover liability if someone gets hurt in your apartment.",
              example: "Your laptop and bike get stolen in a break-in worth $1,800 combined. Without insurance, that's a $1,800 loss. With a $15/month policy, you might pay a $250 deductible and get the rest reimbursed.",
            },
            {
              kind: "teach",
              id: "real-estate-u1-l3-t2",
              title: "The 30% rent guideline",
              body: "A common budgeting rule of thumb is to spend no more than about 30% of your gross (pre-tax) monthly income on rent, so the rest can cover food, transportation, savings, and everything else.",
              analogy: "It's a screening tool, not a law, think of it like a speed limit sign, a guideline to keep you from overcommitting, not a guarantee of safety.",
            },
            {
              kind: "question",
              id: "real-estate-u1-l3-q1",
              type: "mcq",
              prompt: "Renters insurance primarily protects you against which of these?",
              options: [
                "The building's structure being damaged",
                "Your landlord's furniture and appliances",
                "Your personal belongings and personal liability",
                "Rent increases from your landlord",
              ],
              correctIndex: 2,
              explanation: "Renters insurance covers YOUR stuff (electronics, furniture, clothes) and liability if someone is injured in your unit, the building itself is covered by the landlord's separate policy.",
              hint: "The landlord already insures the building itself.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l3-q2",
              type: "scenario",
              context: "You and 3 roommates want to split a 3-bedroom apartment listed at $2,800/month total. One bedroom is a bit bigger, so you're deciding how to split fairly.",
              prompt: "If split evenly four ways, how much does each roommate owe per month?",
              options: ["$600", "$700", "$800", "$933"],
              correctIndex: 1,
              explanation: "$2,800 ÷ 4 = $700 per person if split evenly. (Many roommates instead adjust shares slightly based on room size, e.g., the bigger room pays a bit more.)",
              hint: "Divide the total rent by the number of roommates.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u1-l3-q3",
              type: "scenario",
              context: "You take a part-time job earning $2,200/month (gross) while in school. You're looking at a room for $750/month.",
              prompt: "Using the 30% guideline, is $750/month rent within a comfortable range?",
              options: [
                "Yes, it's under 30% of your gross income",
                "No, it's over 30% of your gross income",
                "The 30% rule doesn't apply to part-time income",
                "It's exactly 50%, which is ideal",
              ],
              correctIndex: 1,
              explanation: "30% of $2,200 is $660. At $750/month, rent would eat about 34% of gross income, above the guideline, meaning less room for other expenses.",
              hint: "Calculate 30% of $2,200 first, then compare it to $750.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u1-l4",
          unitId: "real-estate-u1",
          courseId: "real-estate",
          order: 4,
          title: "Unit 1 Challenge: Renting Roundup",
          difficulty: "Beginner",
          kind: "challenge",
          xp: 75,
          summary: "Prove you can navigate a lease, protect your deposit, and budget rent like a pro.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u1-l4-t1",
              title: "Quick recap before you're tested",
              body: "Leases bind you for the full term with joint liability if you have roommates, deposits come back based on documented condition (not memory), renters insurance is cheap protection for your stuff, and the 30% rule keeps rent from swallowing your budget.",
            },
            {
              kind: "question",
              id: "real-estate-u1-l4-q1",
              type: "scenario",
              context: "You and 3 roommates signed a 12-month lease at $3,200/month total. Six months in, one roommate moves out without telling the landlord and stops paying.",
              prompt: "Legally, what happens to the remaining rent obligation?",
              options: [
                "It automatically drops to $2,400/month for the group",
                "The remaining roommates can be held liable for the full $3,200/month",
                "The landlord must evict everyone immediately",
                "The lease becomes void",
              ],
              correctIndex: 1,
              explanation: "Joint and several liability means the full rent obligation doesn't shrink just because one signer leaves, the remaining roommates can be pursued for the complete amount.",
              hint: "Remember what 'joint and several' liability means.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u1-l4-q2",
              type: "true-false",
              prompt: "Taking dated photos of your apartment on move-in day has no real legal value when it comes time to get your deposit back.",
              correctBool: false,
              explanation: "Move-in photos are one of the strongest pieces of evidence you can have, they prove the unit's condition before you lived there, which protects you from being blamed for pre-existing issues.",
              hint: "Think about what happens in a deposit dispute without proof.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u1-l4-q3",
              type: "fill-in",
              prompt: "A monthly insurance policy that covers your personal belongings in a rental (but not the building itself) is called ___ insurance.",
              accept: ["renters", "renter's", "renter"],
              explanation: "Renters insurance protects your belongings and provides liability coverage, the building itself is covered separately by the landlord's policy.",
              hint: "It's named after who's living in the unit, not who owns it.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u1-l4-q4",
              type: "scenario",
              context: "Your gross monthly income is $3,000. You're deciding between a studio at $1,000/month and a shared room at $850/month.",
              prompt: "Which option keeps you within the 30% rent guideline?",
              options: [
                "Only the $850 shared room",
                "Only the $1,000 studio",
                "Both options",
                "Neither option",
              ],
              correctIndex: 0,
              explanation: "30% of $3,000 is $900. The $850 shared room is under that guideline, while the $1,000 studio slightly exceeds it, so only the shared room fits comfortably.",
              hint: "Calculate 30% of $3,000 exactly, then compare both prices to it.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u1-l4-q5",
              type: "mcq",
              prompt: "Your landlord withholds part of your deposit for 'carpet replacement' after 2 years of normal living. What's your best first move?",
              options: [
                "Pay it immediately without question",
                "Request an itemized deduction list and compare it against your move-in documentation",
                "Post about it on social media instead of contacting the landlord",
                "Assume all deposit deductions are automatically fair",
              ],
              correctIndex: 1,
              explanation: "An itemized list lets you check whether the deduction is for actual damage or just normal wear and tear, which typically can't be charged to you after two years of regular use.",
              hint: "You have a right to see exactly what you're being charged for and why.",
              xp: 15,
            },
          ],
        },
      ],
    },

    // ────────────────────────────────────────────────────────────────
    // UNIT 2: How Buying Works
    // ────────────────────────────────────────────────────────────────
    {
      id: "real-estate-u2",
      courseId: "real-estate",
      order: 2,
      title: "How Buying Works",
      subtitle: "Mortgages, down payments, PMI, and what actually shows up in a monthly payment",
      lessons: [
        {
          id: "real-estate-u2-l1",
          unitId: "real-estate-u2",
          courseId: "real-estate",
          order: 1,
          title: "Mortgage Basics",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "Principal, interest, and why a 15-year loan costs less overall than a 30-year one.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u2-l1-t1",
              title: "Principal vs. interest",
              body: "A mortgage payment is split into principal (paying down the actual amount you borrowed) and interest (the cost of borrowing that money). Early in the loan, most of your payment goes toward interest, over time, that flips.",
              example: "On a $300,000 mortgage at 6.5%, your very first payment is mostly interest, only a small slice actually reduces the $300,000 balance.",
            },
            {
              kind: "teach",
              id: "real-estate-u2-l1-t2",
              title: "30-year vs. 15-year terms",
              body: "A 30-year mortgage has lower monthly payments but you pay far more total interest over the life of the loan. A 15-year mortgage has higher monthly payments but builds equity faster and costs significantly less in total interest.",
              analogy: "It's like paying off a big debt in small bites over a long time (30-year) versus fewer, bigger bites that finish the job faster and cheaper overall (15-year).",
            },
            {
              kind: "question",
              id: "real-estate-u2-l1-q1",
              type: "mcq",
              prompt: "On a $300,000 home loan at 6.5% interest, why is the FIRST monthly payment mostly interest rather than principal?",
              options: [
                "Lenders always charge interest first, then principal, as separate bills",
                "The interest is calculated on the full remaining balance, which is highest at the start",
                "It's a mistake most borrowers can get corrected",
                "Interest only applies during the last few years of the loan",
              ],
              correctIndex: 1,
              explanation: "Interest is calculated on the current balance. Since the balance is largest at the very start of the loan, the interest portion of each payment is largest then too, it shrinks as the balance goes down.",
              hint: "Interest is a percentage of what you still owe.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l1-q2",
              type: "true-false",
              prompt: "A 15-year mortgage almost always has higher monthly payments than a 30-year mortgage on the same loan amount.",
              correctBool: true,
              explanation: "Because you're paying off the same balance in half the time, monthly payments are higher, but you typically pay much less total interest over the life of the loan.",
              hint: "Think about squeezing the same loan into fewer years.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l1-q3",
              type: "scenario",
              context: "A student's parents are comparing a 30-year mortgage at $1,896/month to a 15-year mortgage at $2,614/month, both for a $300,000 home at 6.5%.",
              prompt: "Why might someone still choose the 30-year option even though it costs more in total interest?",
              options: [
                "It always builds equity faster",
                "Lower monthly payments give more budget flexibility today",
                "30-year loans have no interest at all",
                "It's required by law for first-time buyers",
              ],
              correctIndex: 1,
              explanation: "The tradeoff is real: 30-year loans cost more in total interest but free up monthly cash flow, which can matter a lot depending on someone's income and other financial goals.",
              hint: "Think about what changes month-to-month, not over the life of the loan.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u2-l2",
          unitId: "real-estate-u2",
          courseId: "real-estate",
          order: 2,
          title: "Down Payments & PMI",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "You don't need 20% down, but skipping it usually costs you PMI.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u2-l2-t1",
              title: "The 20% down payment myth",
              body: "Many people believe you must put 20% down to buy a home, but that's not true, FHA loans allow as little as 3.5% down, and some conventional loans go even lower. 20% is a benchmark, not a requirement.",
              example: "On a $300,000 home, 20% down is $60,000. An FHA loan at 3.5% down would only require $10,500 upfront.",
            },
            {
              kind: "teach",
              id: "real-estate-u2-l2-t2",
              title: "PMI: the cost of a smaller down payment",
              body: "If you put down less than 20%, lenders usually require Private Mortgage Insurance (PMI), typically 0.5%, 1.5% of the loan amount per year, which protects the LENDER (not you) if you default. It usually goes away once you reach 20% equity.",
              analogy: "PMI is like a lender's insurance policy on your ability to pay, you foot the bill, but the payout protects them, not you.",
            },
            {
              kind: "question",
              id: "real-estate-u2-l2-q1",
              type: "mcq",
              prompt: "What is PMI (Private Mortgage Insurance) designed to protect?",
              options: [
                "The homebuyer's monthly budget",
                "The lender, in case the borrower defaults",
                "The home's resale value",
                "The buyer's credit score",
              ],
              correctIndex: 1,
              explanation: "PMI protects the lender's investment, not the borrower, it's the tradeoff for being allowed to buy with a smaller down payment.",
              hint: "Who takes on more risk when the down payment is smaller?",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l2-q2",
              type: "fill-in",
              prompt: "The FHA loan program allows down payments as low as ___% for qualifying buyers.",
              accept: ["3.5", "3.5%"],
              explanation: "FHA loans can require as little as 3.5% down, far below the commonly assumed 20% benchmark.",
              hint: "It's a small number, less than 5%.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l2-q3",
              type: "scenario",
              context: "A buyer purchases a $250,000 home with only 5% down ($12,500), using a conventional loan.",
              prompt: "What should they expect as a result of the small down payment?",
              options: [
                "No extra cost, down payment size doesn't affect anything",
                "They'll likely have to pay PMI until they reach 20% equity",
                "The lender will refuse the loan entirely",
                "Their interest rate will drop automatically",
              ],
              correctIndex: 1,
              explanation: "Putting down less than 20% on a conventional loan typically triggers PMI, an added monthly cost until enough equity is built up (often through payments or appreciation).",
              hint: "Think about what protects the lender when the down payment is small.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u2-l3",
          unitId: "real-estate-u2",
          courseId: "real-estate",
          order: 3,
          title: "Closing Costs & PITI",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "The extra 2-5% at closing, and the four pieces that make up your real monthly payment.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u2-l3-t1",
              title: "Closing costs sneak up on buyers",
              body: "Beyond the down payment, buyers typically pay 2%, 5% of the home's price in closing costs, covering things like loan origination fees, appraisal, title insurance, and inspection.",
              example: "On a $300,000 home, closing costs could run $6,000, $15,000, due at signing on top of the down payment.",
            },
            {
              kind: "teach",
              id: "real-estate-u2-l3-t2",
              title: "PITI: what's really in your monthly payment",
              body: "Your true monthly housing payment usually isn't just the mortgage, it's PITI: Principal, Interest, Taxes, and Insurance, all bundled into one payment by most lenders.",
              analogy: "PITI is like a subscription bundle, instead of paying the mortgage company, the tax office, and the insurance company separately, one payment covers all four pieces.",
            },
            {
              kind: "question",
              id: "real-estate-u2-l3-q1",
              type: "fill-in",
              prompt: "The acronym for the four components of a typical monthly mortgage payment is ___.",
              accept: ["piti"],
              explanation: "PITI stands for Principal, Interest, Taxes, and Insurance, the full picture of what a monthly housing payment usually includes.",
              hint: "It's a 4-letter acronym.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l3-q2",
              type: "true-false",
              prompt: "Closing costs are typically included in your down payment, not an additional expense.",
              correctBool: false,
              explanation: "Closing costs (2-5% of the price) are separate from the down payment, buyers need to budget for both amounts of cash at signing.",
              hint: "These are two distinct cash requirements at the closing table.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u2-l3-q3",
              type: "scenario",
              context: "A student's older sibling is buying a $280,000 condo. They've saved $28,000 for a 10% down payment but forgot to budget for closing costs.",
              prompt: "Roughly how much extra should they expect to need at closing (using the 2-5% guideline)?",
              options: ["$500-$1,000", "$1,400-$2,000", "$5,600-$14,000", "$28,000-$56,000"],
              correctIndex: 2,
              explanation: "2%-5% of $280,000 is $5,600-$14,000, a real cash requirement on top of the down payment that catches many first-time buyers off guard.",
              hint: "Multiply $280,000 by 2% and by 5% to find the range.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u2-l4",
          unitId: "real-estate-u2",
          courseId: "real-estate",
          order: 4,
          title: "Unit 2 Challenge: The Buying Process",
          difficulty: "Intermediate",
          kind: "challenge",
          xp: 85,
          summary: "Show you understand mortgages, down payments, PMI, and PITI well enough to size up a real purchase.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u2-l4-t1",
              title: "Quick recap before you're tested",
              body: "Mortgages split into principal and interest, with 15-year loans costing less overall but demanding higher payments. Down payments can be as low as 3.5% (FHA), but under 20% usually means PMI. Closing costs add another 2-5%, and your real monthly cost is PITI, not just principal and interest.",
            },
            {
              kind: "question",
              id: "real-estate-u2-l4-q1",
              type: "scenario",
              context: "A buyer takes out a $320,000 mortgage at 6.5% with only 10% down.",
              prompt: "Which of the following will most likely apply to this loan?",
              options: [
                "No PMI, since 10% is close enough to 20%",
                "PMI, until they reach roughly 20% equity",
                "A discount on their interest rate",
                "An automatic waiver of closing costs",
              ],
              correctIndex: 1,
              explanation: "Putting down less than 20% on a conventional loan almost always triggers PMI, which continues until enough equity is built.",
              hint: "PMI kicks in below a specific equity threshold.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u2-l4-q2",
              type: "fill-in",
              prompt: "PITI includes principal, interest, taxes, and ___.",
              accept: ["insurance"],
              explanation: "The 'I' at the end of PITI stands for insurance, typically homeowners insurance bundled into the monthly payment.",
              hint: "It's the same word used for renters insurance, just for owners.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u2-l4-q3",
              type: "true-false",
              prompt: "A 30-year mortgage always results in less total interest paid than a 15-year mortgage on the same loan amount.",
              correctBool: false,
              explanation: "The opposite is true, a 30-year loan spreads payments out longer, which means more total interest paid over the life of the loan, even though monthly payments are lower.",
              hint: "Think about how many years of interest accrue on each option.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u2-l4-q4",
              type: "mcq",
              prompt: "A home is priced at $340,000. Using the 2-5% guideline, what's a reasonable estimate for closing costs?",
              options: ["$340-$1,700", "$3,400-$5,000", "$6,800-$17,000", "$34,000-$68,000"],
              correctIndex: 2,
              explanation: "2% of $340,000 is $6,800 and 5% is $17,000, giving a realistic closing cost range buyers should budget for on top of the down payment.",
              hint: "Calculate 2% and 5% of $340,000 separately.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u2-l4-q5",
              type: "scenario",
              context: "Two buyers each borrow $300,000 at 6.5%. Buyer A chooses a 30-year term; Buyer B chooses a 15-year term.",
              prompt: "Which statement is most accurate?",
              options: [
                "Buyer A pays less monthly but more total interest over the loan",
                "Buyer B pays less monthly but more total interest over the loan",
                "Both buyers pay identical monthly payments",
                "Loan term has no effect on monthly payment or total interest",
              ],
              correctIndex: 0,
              explanation: "Buyer A's 30-year term spreads the same balance over more payments, lowering each monthly payment but increasing the total interest paid over the life of the loan compared to Buyer B's 15-year term.",
              hint: "Longer terms mean smaller bites each month, but more bites total.",
              xp: 15,
            },
          ],
        },
      ],
    },

    // ────────────────────────────────────────────────────────────────
    // UNIT 3: Property as an Investment
    // ────────────────────────────────────────────────────────────────
    {
      id: "real-estate-u3",
      courseId: "real-estate",
      order: 3,
      title: "Property as an Investment",
      subtitle: "House hacking, rental cash flow, REITs, and cap rate math",
      lessons: [
        {
          id: "real-estate-u3-l1",
          unitId: "real-estate-u3",
          courseId: "real-estate",
          order: 1,
          title: "House Hacking",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Buy a duplex, live in one side, rent the other, and let a stranger help pay your mortgage.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u3-l1-t1",
              title: "What house hacking actually means",
              body: "House hacking means buying a multi-unit property (like a duplex), living in one unit, and renting out the other(s), the rental income offsets or fully covers your mortgage, letting you live for cheap (or free) while building equity.",
              example: "You buy a duplex with a $2,200/month mortgage. You live in one unit and rent the other for $1,400/month, so your real out-of-pocket housing cost drops to just $800/month.",
            },
            {
              kind: "teach",
              id: "real-estate-u3-l1-t2",
              title: "Why lenders like it too",
              body: "Because you're living in the property, you can often qualify for owner-occupant loan terms (like a low down payment) even though part of the building is a rental, terms that wouldn't be available if you bought it purely as an investor.",
              analogy: "It's like getting a roommate, except the 'roommate' lives in a separate legal unit and their rent check goes straight at your mortgage bill.",
            },
            {
              kind: "question",
              id: "real-estate-u3-l1-q1",
              type: "scenario",
              context: "A recent grad buys a duplex with a $2,400/month mortgage. They live in Unit A and rent Unit B for $1,500/month.",
              prompt: "What is their actual monthly out-of-pocket housing cost?",
              options: ["$2,400", "$1,500", "$900", "$0"],
              correctIndex: 2,
              explanation: "$2,400 mortgage minus $1,500 in rental income leaves $900/month in real out-of-pocket cost, significantly less than paying the full mortgage alone.",
              hint: "Subtract the rental income from the total mortgage payment.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l1-q2",
              type: "mcq",
              prompt: "What is the core idea behind 'house hacking'?",
              options: [
                "Illegally modifying a property to add units",
                "Living in part of a property while renting out the rest to offset costs",
                "Flipping a house for quick profit",
                "Renting an entire property and subletting all of it",
              ],
              correctIndex: 1,
              explanation: "House hacking is about occupying part of a multi-unit property while renting the rest, using that rental income to reduce your own housing costs.",
              hint: "The word 'hack' here means a clever shortcut, not something illegal.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l1-q3",
              type: "true-false",
              prompt: "Because you live in the property, house hackers can sometimes qualify for owner-occupant loan terms not available to pure investors.",
              correctBool: true,
              explanation: "Lenders often offer more favorable terms (like lower down payments) to owner-occupants than to investors buying purely rental property, which is part of what makes house hacking attractive.",
              hint: "Think about how lenders view risk differently for owners vs. investors.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u3-l2",
          unitId: "real-estate-u3",
          courseId: "real-estate",
          order: 2,
          title: "Rental Cash Flow & the 1% Rule",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "The real math behind whether a rental property actually makes money.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u3-l2-t1",
              title: "Cash flow is what's left after everything",
              body: "Cash flow = rental income minus the mortgage payment minus expenses (maintenance, vacancy, property management, taxes, insurance). Positive cash flow means the property pays you; negative means you're subsidizing it.",
              example: "Rent is $1,800/month. Mortgage is $1,300. Other expenses run $300/month. Cash flow = $1,800 − $1,300 − $300 = $200/month in your pocket.",
            },
            {
              kind: "teach",
              id: "real-estate-u3-l2-t2",
              title: "The 1% rule (a quick screening tool)",
              body: "The 1% rule says a rental property's monthly rent should be roughly 1% or more of its purchase price to be worth a closer look. It's a fast filter, not a guarantee of profitability, you still need to run real numbers.",
              analogy: "Think of it like a first date screening question, passing doesn't mean it's 'the one,' but failing it usually means don't bother going further.",
            },
            {
              kind: "question",
              id: "real-estate-u3-l2-q1",
              type: "scenario",
              context: "A rental property collects $1,800/month in rent. The mortgage is $1,300/month, and other expenses (repairs, insurance, vacancy reserve) run $300/month.",
              prompt: "What is the monthly cash flow?",
              options: ["$3,400", "$500", "$200", "-$200"],
              correctIndex: 2,
              explanation: "$1,800 − $1,300 − $300 = $200/month positive cash flow, meaning the property is generating profit after all costs.",
              hint: "Subtract both the mortgage and expenses from the rent collected.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l2-q2",
              type: "mcq",
              prompt: "A property is priced at $200,000. According to the 1% rule, what monthly rent would make it worth a closer look?",
              options: ["$200", "$1,000", "$2,000", "$20,000"],
              correctIndex: 2,
              explanation: "1% of $200,000 is $2,000/month, that's the rough benchmark the 1% rule uses to flag a property as potentially worth deeper analysis.",
              hint: "Calculate 1% of the purchase price.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l2-q3",
              type: "true-false",
              prompt: "Passing the 1% rule guarantees a rental property will be profitable.",
              correctBool: false,
              explanation: "The 1% rule is only a rough screening tool to quickly filter properties, real profitability depends on actual expenses, vacancy rates, financing terms, and local market conditions.",
              hint: "Quick rules of thumb are starting points, not final answers.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u3-l3",
          unitId: "real-estate-u3",
          courseId: "real-estate",
          order: 3,
          title: "REITs & Cap Rate",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Own real estate through the stock market, and learn the formula pros use to value a property.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u3-l3-t1",
              title: "REITs: real estate without the landlord headaches",
              body: "A REIT (Real Estate Investment Trust) is a company that owns income-producing real estate and trades like a stock, you can invest with as little as $50, earn dividends from the rental income, and sell your shares any time, unlike owning a physical property.",
              example: "Instead of saving $60,000 for a rental property down payment, you buy $50 of REIT shares and instantly own a small slice of a portfolio of apartment buildings or shopping centers.",
            },
            {
              kind: "teach",
              id: "real-estate-u3-l3-t2",
              title: "Cap rate: how investors value a property",
              body: "Cap rate (capitalization rate) = Net Operating Income (NOI) ÷ Property Price. It tells you the annual return a property generates before financing, and lets investors compare properties of different sizes and prices.",
              example: "A property has $24,000 in annual NOI and costs $400,000. Cap rate = $24,000 ÷ $400,000 = 6%.",
            },
            {
              kind: "question",
              id: "real-estate-u3-l3-q1",
              type: "mcq",
              prompt: "What is a key advantage of REITs over owning physical rental property directly?",
              options: [
                "REITs require a large down payment, just like a house",
                "REITs offer more liquidity, shares can be bought or sold quickly",
                "REITs eliminate all investment risk",
                "REITs require you to personally manage tenants",
              ],
              correctIndex: 1,
              explanation: "REITs trade like stocks, so you can buy or sell shares almost instantly, unlike a physical property, which can take months to sell.",
              hint: "Think about how fast you can convert an investment back to cash.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l3-q2",
              type: "fill-in",
              prompt: "Cap rate is calculated as Net Operating Income divided by ___.",
              accept: ["price", "property price", "purchase price"],
              explanation: "Cap rate = NOI ÷ Property Price, giving investors a way to compare the return potential of different properties.",
              hint: "It's the denominator that represents how much the property costs.",
              xp: 10,
            },
            {
              kind: "question",
              id: "real-estate-u3-l3-q3",
              type: "scenario",
              context: "A small apartment building generates $36,000 in annual net operating income and is listed for sale at $600,000.",
              prompt: "What is its cap rate?",
              options: ["3%", "6%", "9%", "12%"],
              correctIndex: 1,
              explanation: "$36,000 ÷ $600,000 = 0.06, or 6% cap rate, a common range for evaluating income properties, though 'good' varies heavily by market.",
              hint: "Divide the NOI by the price and convert to a percentage.",
              xp: 10,
            },
          ],
        },
        {
          id: "real-estate-u3-l4",
          unitId: "real-estate-u3",
          courseId: "real-estate",
          order: 4,
          title: "Unit 3 Challenge: Investing in Property",
          difficulty: "Advanced",
          kind: "challenge",
          xp: 95,
          summary: "Test your grasp of house hacking, cash flow, REITs, cap rate, and how leverage cuts both ways.",
          cards: [
            {
              kind: "teach",
              id: "real-estate-u3-l4-t1",
              title: "Quick recap before you're tested",
              body: "House hacking uses rental income to offset your own mortgage. Cash flow is rent minus mortgage minus expenses, screened quickly with the 1% rule. REITs let you invest in real estate with small amounts and high liquidity. Cap rate (NOI ÷ price) values a property's return. And leverage, using a mortgage to control a bigger asset, can amplify both gains and losses.",
            },
            {
              kind: "question",
              id: "real-estate-u3-l4-q1",
              type: "scenario",
              context: "A buyer purchases a duplex with a $2,600/month mortgage, lives in one unit, and rents the other for $1,700/month. Other monthly expenses (maintenance, insurance) run $200.",
              prompt: "What is their real net monthly housing cost?",
              options: ["$2,600", "$1,100", "$900", "$700"],
              correctIndex: 1,
              explanation: "$2,600 mortgage + $200 expenses − $1,700 rental income = $1,100/month net cost, far less than paying the full mortgage and expenses alone.",
              hint: "Add the mortgage and expenses first, then subtract the rent collected.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u3-l4-q2",
              type: "mcq",
              prompt: "A $350,000 property generates $2,000/month in rent. Does it pass the 1% rule screen?",
              options: [
                "Yes, $2,000 is above 1% of $350,000",
                "No, $2,000 is below 1% of $350,000",
                "The 1% rule doesn't apply to residential property",
                "It exactly meets the rule with no margin",
              ],
              correctIndex: 1,
              explanation: "1% of $350,000 is $3,500/month. At only $2,000/month, this property falls well short of the 1% rule screen, suggesting a closer look at expenses before buying.",
              hint: "Find 1% of $350,000 and compare it to the rent.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u3-l4-q3",
              type: "fill-in",
              prompt: "A company that owns income-producing real estate and trades like a stock, letting you invest with as little as $50, is called a ___.",
              accept: ["reit", "real estate investment trust"],
              explanation: "A REIT (Real Estate Investment Trust) lets everyday investors own a slice of real estate income streams without buying physical property.",
              hint: "It's a 4-letter acronym.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u3-l4-q4",
              type: "scenario",
              context: "A property generates $45,000 in annual NOI and is priced at $750,000.",
              prompt: "What is its cap rate?",
              options: ["4%", "6%", "9%", "15%"],
              correctIndex: 1,
              explanation: "$45,000 ÷ $750,000 = 0.06, or a 6% cap rate.",
              hint: "Divide NOI by price to get a decimal, then convert to a percentage.",
              xp: 15,
            },
            {
              kind: "question",
              id: "real-estate-u3-l4-q5",
              type: "true-false",
              prompt: "Because leverage (using borrowed money) can amplify gains when a property's value rises, it also amplifies losses if the value falls.",
              correctBool: true,
              explanation: "Leverage is a double-edged sword, a small down payment means a rise in property value produces a large percentage return on your cash, but a decline in value can wipe out that same cash even faster.",
              hint: "Think about what happens to your % return when you've only put down a small fraction of the price.",
              xp: 15,
            },
          ],
        },
      ],
    },
  ],
};
