import type { Course } from "@/lib/types";

export const salesNetworkingCourse: Course = {
  id: "sales-networking",
  title: "Sales & Networking",
  tagline: "Learn to open doors, pitch yourself, and build relationships that actually pay off.",
  description:
    "Cold emails, elevator pitches, coffee chats, and closing the ask, sales and networking are the same skill wearing different outfits. This course teaches you the exact scripts and mindsets that turn strangers into contacts, contacts into opportunities, and opportunities into offers.",
  category: "Career",
  icon: "Handshake",
  color: "from-rose-500 to-fuchsia-500",
  accent: "rose-300",
  order: 6,
  unlockLevel: 2,
  units: [
    // ─────────────────────────────────────────────────────────────────
    // Unit 1: Talking to Humans
    // ─────────────────────────────────────────────────────────────────
    {
      id: "sales-networking-u1",
      courseId: "sales-networking",
      order: 1,
      title: "Talking to Humans",
      subtitle: "Cold outreach, elevator pitches, and LinkedIn that doesn't feel fake",
      lessons: [
        {
          id: "sales-networking-u1-l1",
          unitId: "sales-networking-u1",
          courseId: "sales-networking",
          order: 1,
          title: "The Cold Outreach Formula",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "A 3-part formula for messaging strangers that actually gets replies.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u1-l1-t1",
              title: "Nobody replies to 'I'd love to connect'",
              body: "Generic outreach gets ignored because it takes zero effort and signals you didn't do any research either. The fix is a simple 3-part formula: a specific compliment or context, a one-line who-you-are, and one small clear ask.",
              example:
                "\"I saw your post about switching from consulting to product management, I'm a sophomore exploring the same move. Would you have 15 minutes this month for 2-3 questions about how you made the jump?\"",
            },
            {
              kind: "teach",
              id: "sales-networking-u1-l1-t2",
              title: "Keep it under 100 words",
              body: "Busy people skim. A message that takes 10 seconds to read gets 10x more replies than a 3-paragraph life story. Say less, ask for less, and make the ask easy to say yes to.",
              analogy: "Think of a cold message like a text, not an email essay, if it needs scrolling, it needs cutting.",
            },
            {
              kind: "question",
              id: "sales-networking-u1-l1-q1",
              type: "mcq",
              prompt: "What are the three parts of the cold outreach formula?",
              options: [
                "Compliment/context, who you are, one small clear ask",
                "Introduction, resume attachment, thank you",
                "Flattery, long backstory, job request",
                "Greeting, company facts, meeting link",
              ],
              correctIndex: 0,
              explanation:
                "Specific context proves you did your homework, a one-line intro gives them just enough to place you, and a small ask makes it easy to say yes.",
              hint: "It starts with proving you're not a copy-paste spammer.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l1-q2",
              type: "scenario",
              prompt: "Which opener is most likely to get a reply?",
              context:
                "You want to message a Campus Capital alum who now works in venture capital. You found her on LinkedIn and saw she recently spoke on a fintech panel at your school.",
              options: [
                "\"Hi, I'd love to pick your brain sometime, are you free?\"",
                "\"I watched your fintech panel talk last week, your point about student lending stuck with me. I'm a junior interested in VC and would love 15 minutes to ask 2 questions about how you broke in.\"",
                "\"Hey! Big fan, can you get me an internship?\"",
                "\"Dear Ms. Reyes, I am writing to inquire about potential employment opportunities at your firm.\"",
              ],
              correctIndex: 1,
              explanation:
                "It references something specific (the panel), states who you are, and asks for something small and time-bound (15 minutes, 2 questions) instead of a vague favor.",
              hint: "Look for specific context plus a small, concrete ask.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l1-q3",
              type: "true-false",
              prompt: "A cold message should always end with a direct ask for a job or internship.",
              correctBool: false,
              explanation:
                "Asking for a job in a first message feels transactional and puts people on the defensive. Ask for something small like advice or 15 minutes, the job conversation comes later, if at all.",
              hint: "Think about what feels low-pressure to the person receiving it.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l1-q4",
              type: "fill-in",
              prompt: "Fill in the blank: A good cold message should be under ___ words.",
              accept: ["100", "100 words"],
              explanation: "Under 100 words keeps the message skimmable and respects the reader's time, which makes them far more likely to actually respond.",
              hint: "It's the same number mentioned in the teach card above.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u1-l2",
          unitId: "sales-networking-u1",
          courseId: "sales-networking",
          order: 2,
          title: "The 30-Second Elevator Pitch",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Build a pitch you can say in the time it takes an elevator to move a few floors.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u1-l2-t1",
              title: "Four pieces, thirty seconds",
              body: "A strong elevator pitch has four parts: your name, what you do (major, year, focus), a proof point that makes you credible, and what you're looking for. Skip any part and the pitch feels either arrogant or vague.",
              example:
                "\"Hi, I'm Jordan, I'm a junior finance major who runs my school's investing club, where we grew our paper portfolio 18% last semester. I'm looking for a summer analyst role and would love to hear about your team.\"",
            },
            {
              kind: "teach",
              id: "sales-networking-u1-l2-t2",
              title: "The proof point is what makes it land",
              body: "'I'm interested in finance' is forgettable. A number, a project, or a result is not. Even small proof points, a club, a class project, a competition, make you sound credible instead of just enthusiastic.",
              analogy: "The proof point is the receipt, anyone can claim interest, but a receipt shows you actually did something.",
            },
            {
              kind: "question",
              id: "sales-networking-u1-l2-q1",
              type: "mcq",
              prompt: "Which element is missing from this pitch: 'Hi, I'm Sam, a sophomore studying marketing. I ran our club's social media and grew followers by 40%.'",
              options: [
                "Your name",
                "What you're looking for",
                "A proof point",
                "Your major",
              ],
              correctIndex: 1,
              explanation:
                "The pitch has a name, major, and a strong proof point (40% growth), but never says what Sam actually wants, an internship, a contact, advice.",
              hint: "The pitch ends with a fact, not a request.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l2-q2",
              type: "scenario",
              prompt: "Which pitch is strongest for a career fair table?",
              context:
                "You're standing in front of a recruiter at a career fair booth with about 30 seconds before the next student cuts in line.",
              options: [
                "\"I'm really passionate about your company and would do anything to work here.\"",
                "\"Hi, I'm Priya, a junior in computer science. I built a class project that automated our department's event sign-ups, and I'm looking for a summer software internship, what does your intern team usually work on?\"",
                "\"So tell me about your company, what do you guys even do?\"",
                "\"I don't have much experience yet but I'm a fast learner and hard worker.\"",
              ],
              correctIndex: 1,
              explanation:
                "It hits all four parts fast, name, major, a concrete proof point, and a specific ask, then hands the conversation back with a question.",
              hint: "Look for the one with a name, a proof point, and a specific ask, not just enthusiasm.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l2-q3",
              type: "true-false",
              prompt: "A good elevator pitch should end with a question or ask, not just trail off.",
              correctBool: true,
              explanation: "Ending with a clear ask or question keeps the conversation moving and shows you know what you want from the interaction.",
              hint: "Think about what happens if you just stop talking after your proof point.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l2-q4",
              type: "fill-in",
              prompt: "Fill in the blank: The four parts of an elevator pitch are name, what you do, a ___ point, and what you're looking for.",
              accept: ["proof", "proof point"],
              explanation: "The proof point is the specific result, project, or number that makes the rest of your pitch credible instead of just a claim.",
              hint: "It's the part that acts like evidence.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u1-l3",
          unitId: "sales-networking-u1",
          courseId: "sales-networking",
          order: 3,
          title: "LinkedIn That Actually Works",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Fix the profile and connection habits that make students invisible.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u1-l3-t1",
              title: "'Student at [School]' is a wasted headline",
              body: "Your headline is prime real estate, it's the first thing anyone sees before deciding whether to click your profile. Replace 'Student at State University' with what you actually do or are working toward, like 'Finance Student | Investing Club VP | Aspiring Analyst.'",
              example:
                "Compare 'Student at Northview University' to 'Marketing Sophomore Building Growth Campaigns for Local Small Businesses', the second one gives a recruiter a reason to click.",
            },
            {
              kind: "teach",
              id: "sales-networking-u1-l3-t2",
              title: "Never send a blank connection request",
              body: "A blank request looks like spam and gets ignored or declined. A short note explaining why you're connecting, a shared class, mutual interest, or event, dramatically increases acceptance rates.",
            },
            {
              kind: "teach",
              id: "sales-networking-u1-l3-t3",
              title: "Engage before you ask",
              body: "Commenting thoughtfully on someone's posts for a few weeks before messaging them makes your name familiar, so your eventual ask lands with someone who already half-recognizes you.",
              analogy: "It's the difference between a stranger asking for your number and someone you've bumped into at the same coffee shop three times.",
            },
            {
              kind: "question",
              id: "sales-networking-u1-l3-q1",
              type: "mcq",
              prompt: "Why is 'Student at [School]' a weak LinkedIn headline?",
              options: [
                "It's too short to fit the character limit",
                "It gives no reason for someone to click into your profile",
                "LinkedIn hides profiles with that headline",
                "It's against LinkedIn's terms of service",
              ],
              correctIndex: 1,
              explanation:
                "The headline is your pitch in the search results, a generic one gives recruiters and alumni zero reason to open your profile over anyone else's.",
              hint: "Think about what a recruiter sees before ever clicking your name.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l3-q2",
              type: "true-false",
              prompt: "Sending a connection request with no note is just as effective as one with a short, specific note.",
              correctBool: false,
              explanation:
                "A note that explains the shared context or reason for connecting significantly increases acceptance rates compared to a blank request, which reads as spam.",
              hint: "Would you accept a request from a stranger with zero explanation?",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l3-q3",
              type: "scenario",
              prompt: "What's the best next move?",
              context:
                "You want to connect with a startup founder who spoke at your school's entrepreneurship week. You haven't interacted with her online before.",
              options: [
                "Send a blank connection request immediately",
                "Comment thoughtfully on a couple of her recent posts first, then send a connection request referencing her talk",
                "Wait for her to follow you first",
                "Message her personal Instagram instead",
              ],
              correctIndex: 1,
              explanation:
                "Engaging first makes your name familiar, and referencing her talk in the request gives specific context that makes acceptance far more likely.",
              hint: "Building familiarity before asking usually beats a cold blank request.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l3-q4",
              type: "fill-in",
              prompt: "Fill in the blank: Your LinkedIn ___ is the first thing people see and should say what you do, not just where you study.",
              accept: ["headline"],
              explanation: "Your headline appears next to your name everywhere on LinkedIn, so a specific one gives people a reason to click into your full profile.",
              hint: "It's the line right under your name.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u1-l4",
          unitId: "sales-networking-u1",
          courseId: "sales-networking",
          order: 4,
          title: "Unit 1 Challenge: Talking to Humans",
          difficulty: "Beginner",
          kind: "challenge",
          xp: 75,
          summary: "Prove you can craft outreach, pitches, and profiles that get responses.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u1-l4-t1",
              title: "Response-rate reality check",
              body: "Even a well-written cold message typically gets a 10-20% reply rate, that's normal, not a sign you're bad at this. If you haven't heard back after 5-7 days, one polite follow-up is expected and often what actually gets the reply.",
            },
            {
              kind: "question",
              id: "sales-networking-u1-l4-q1",
              type: "mcq",
              prompt: "You sent 10 well-crafted cold messages to alumni and got 1 reply. What should you conclude?",
              options: [
                "Your messages must be badly written",
                "This is roughly within the normal 10-20% reply rate, keep sending and follow up on the rest",
                "Cold outreach doesn't work and you should stop",
                "You should message the same people again immediately",
              ],
              correctIndex: 1,
              explanation:
                "A 10% reply rate is on the low end of normal, not a failure signal. The move is to follow up once on the non-responders after about a week, not to abandon the approach.",
              hint: "What reply rate range did the lesson call 'normal'?",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l4-q2",
              type: "scenario",
              prompt: "How should you follow up?",
              context:
                "You messaged an alum 6 days ago asking for 15 minutes of her time and haven't heard back. She hasn't posted or shown any sign she's ignoring you on purpose.",
              options: [
                "Never follow up, one message is all you get",
                "Send a short, polite follow-up referencing your original message, since it's now been about a week",
                "Message her three more times in one day",
                "Ask a mutual friend to pressure her into responding",
              ],
              correctIndex: 1,
              explanation:
                "Following up once after 5-7 days is expected and professional, people are busy, not necessarily uninterested, and a short nudge often gets the reply.",
              hint: "The lesson gave a specific day range for when to follow up.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l4-q3",
              type: "fill-in",
              prompt: "Fill in the blank: A normal cold outreach reply rate is roughly ___ to 20 percent.",
              accept: ["10"],
              explanation: "10-20% is the realistic range for cold outreach, even when the message is well-written, most replies come from persistence, not perfection.",
              hint: "It's the low end of the range mentioned in this challenge.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l4-q4",
              type: "true-false",
              prompt: "An elevator pitch and a cold message should both include a specific, concrete proof point rather than vague enthusiasm.",
              correctBool: true,
              explanation:
                "Specifics, a project, a number, a shared reference point, are what separate a memorable pitch or message from one that blends into everyone else's.",
              hint: "Think back to what made the strong examples in this unit stand out.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u1-l4-q5",
              type: "scenario",
              prompt: "Which LinkedIn move will help most before you ask this founder for a call?",
              context:
                "A startup founder posts regularly about fundraising lessons. You want to eventually ask her for 15 minutes of advice, but you've never interacted with her account.",
              options: [
                "Ask for the call right away, cold, with no prior interaction",
                "Comment genuinely on a few of her posts over the next couple weeks to build familiarity before reaching out",
                "Follow her and wait silently for months",
                "Only interact after she messages you first",
              ],
              correctIndex: 1,
              explanation:
                "Engaging first builds familiarity so that when you do send the ask, you're not a total stranger, this consistently improves response rates.",
              hint: "Recall the 'engage before you ask' idea from the LinkedIn lesson.",
              xp: 15,
            },
          ],
        },
      ],
    },
    // ─────────────────────────────────────────────────────────────────
    // Unit 2: Sell Without Being Salesy
    // ─────────────────────────────────────────────────────────────────
    {
      id: "sales-networking-u2",
      courseId: "sales-networking",
      order: 2,
      title: "Sell Without Being Salesy",
      subtitle: "Discovery, objections, and follow-ups that don't feel pushy",
      lessons: [
        {
          id: "sales-networking-u2-l1",
          unitId: "sales-networking-u2",
          courseId: "sales-networking",
          order: 1,
          title: "Discovery Beats Pitching",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "Ask before you pitch, and listen more than you talk.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u2-l1-t1",
              title: "Pitching first is a guess. Asking first is data.",
              body: "If you pitch before understanding someone's actual problem, you're guessing what they care about. Ask a few questions first, and your pitch can speak directly to what they just told you matters.",
              example:
                "Before pitching your club's tutoring service to a sponsor, ask what their biggest hiring pain point is, then pitch the exact feature that solves it.",
            },
            {
              kind: "teach",
              id: "sales-networking-u2-l1-t2",
              title: "Aim for 70/30 listening",
              body: "In a strong sales conversation, the other person should be talking about 70% of the time and you about 30%. If you're doing most of the talking, you're pitching blind.",
              analogy: "Think of it like a doctor's visit, a good doctor asks questions before prescribing anything, not after.",
            },
            {
              kind: "question",
              id: "sales-networking-u2-l1-q1",
              type: "mcq",
              prompt: "Why should you ask about someone's problem before pitching your solution?",
              options: [
                "It wastes less of your own time",
                "It lets your pitch directly address what they actually care about instead of guessing",
                "It's a required legal step in sales",
                "It makes the conversation shorter",
              ],
              correctIndex: 1,
              explanation:
                "Discovery turns your pitch from a generic guess into a targeted answer to a specific problem the person just told you they have.",
              hint: "Think about what changes when you know their actual pain point first.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l1-q2",
              type: "scenario",
              prompt: "You're pitching a local coffee shop to sponsor your club's event. What's the best opening move?",
              context:
                "You walk in with a sponsorship deck ready to present, but you've never spoken to the owner before.",
              options: [
                "Launch straight into your full slide deck",
                "Ask the owner what's been hardest about getting more student customers, then tailor your pitch to that",
                "Offer the lowest possible sponsorship price immediately",
                "Ask them to sign a contract on the spot",
              ],
              correctIndex: 1,
              explanation:
                "Asking about their actual challenge first lets you pitch the sponsorship as a direct solution to something they already said they care about.",
              hint: "Discovery comes before the pitch, not after.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l1-q3",
              type: "true-false",
              prompt: "In a strong sales conversation, you should be talking more than the other person to show your expertise.",
              correctBool: false,
              explanation:
                "The 70/30 rule says the other person should be talking about 70% of the time, you learn more, and they feel heard, which builds trust.",
              hint: "Recall the listening ratio from the teach card.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l1-q4",
              type: "fill-in",
              prompt: "Fill in the blank: Aim for roughly a ___/30 listening-to-talking ratio in a sales conversation.",
              accept: ["70"],
              explanation: "70/30 means the other person talks 70% of the time, most of a good sales conversation is listening, not pitching.",
              hint: "It's the larger of the two numbers.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u2-l2",
          unitId: "sales-networking-u2",
          courseId: "sales-networking",
          order: 2,
          title: "Handling Objections",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "'It's too expensive' rarely means what it sounds like, here's how to respond.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u2-l2-t1",
              title: "Acknowledge, clarify, respond",
              body: "When someone objects, resist the urge to argue immediately. First acknowledge their concern, then ask a clarifying question to understand it, then respond directly to what they actually meant.",
              example:
                "\"Totally fair, when you say too expensive, is that compared to other sponsors, or is it more about not seeing the return yet?\"",
            },
            {
              kind: "teach",
              id: "sales-networking-u2-l2-t2",
              title: "'Too expensive' usually means 'unclear value'",
              body: "When someone says a price is too high, they're often really saying they don't yet see enough value to justify it, not that the number itself is wrong. Clarifying the objection almost always reveals which one it is.",
            },
            {
              kind: "question",
              id: "sales-networking-u2-l2-q1",
              type: "mcq",
              prompt: "What's the correct order for handling an objection?",
              options: [
                "Respond, clarify, acknowledge",
                "Acknowledge, clarify, respond",
                "Ignore, repeat pitch, close",
                "Argue, discount, close",
              ],
              correctIndex: 1,
              explanation:
                "Acknowledging first keeps the conversation calm, clarifying reveals what they actually mean, and only then can you respond to the real concern.",
              hint: "You can't respond well to something you haven't clarified yet.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l2-q2",
              type: "scenario",
              prompt: "A club sponsor says, 'That sponsorship tier feels too expensive.' What's the best response?",
              context:
                "You're pitching a $500 sponsorship package to a local business for your finance club's semester events.",
              options: [
                "\"Okay, I'll just lower the price then.\"",
                "\"I hear you, when you say too expensive, is that about the number itself, or more about not seeing enough return yet?\"",
                "\"It's actually a great deal, trust me.\"",
                "\"That's fine, I'll find another sponsor.\"",
              ],
              correctIndex: 1,
              explanation:
                "This acknowledges the concern and asks a clarifying question instead of assuming the objection is purely about price, which often reveals it's really about unclear value.",
              hint: "Acknowledge first, then clarify what 'too expensive' actually means before responding.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l2-q3",
              type: "true-false",
              prompt: "When someone objects to price, immediately offering a discount is usually the best first move.",
              correctBool: false,
              explanation:
                "Jumping to a discount skips clarifying the real concern, often the issue is unclear value, not the actual number, and a discount doesn't fix that.",
              hint: "What comes before 'respond' in the acknowledge-clarify-respond framework?",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l2-q4",
              type: "fill-in",
              prompt: "Fill in the blank: The 3-step objection framework is acknowledge, ___, respond.",
              accept: ["clarify"],
              explanation: "Clarifying comes second, it's the step that reveals what an objection like 'too expensive' actually means before you try to answer it.",
              hint: "It's the step where you ask a follow-up question.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u2-l3",
          unitId: "sales-networking-u2",
          courseId: "sales-networking",
          order: 3,
          title: "The Follow-Up Game",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "Most sales are lost not to rejection, but to giving up too early.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u2-l3-t1",
              title: "It takes more touches than you think",
              body: "Roughly 80% of sales require 5 or more follow-up touches to close, but most people give up after just one attempt. The gap between those two numbers is where most opportunities are lost.",
              example:
                "If you email a sponsor once and never hear back, you've stopped exactly where 44% of salespeople stop, right before the follow-ups that actually convert.",
            },
            {
              kind: "teach",
              id: "sales-networking-u2-l3-t2",
              title: "Ask for the close directly",
              body: "After you've built value and answered objections, don't wait for the other person to bring up next steps, ask directly. A clear, low-pressure ask like 'Does it make sense to move forward?' moves things along far faster than hoping they'll offer.",
            },
            {
              kind: "question",
              id: "sales-networking-u2-l3-q1",
              type: "mcq",
              prompt: "About what percentage of sales require 5 or more follow-up touches?",
              options: ["20%", "80%", "5%", "50%"],
              correctIndex: 1,
              explanation:
                "Roughly 80% of sales need 5+ touches to close, which is exactly why persistence in following up matters more than most people assume.",
              hint: "It's the number that makes most people's one-attempt approach look like the real problem.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l3-q2",
              type: "scenario",
              prompt: "What should you do next?",
              context:
                "You emailed a potential sponsor once two weeks ago with no reply. You're starting to think they're just not interested.",
              options: [
                "Assume they're not interested and move on for good",
                "Send a brief, friendly follow-up, most deals take multiple touches, not one",
                "Show up at their office unannounced and demand an answer",
                "Wait indefinitely for them to respond first",
              ],
              correctIndex: 1,
              explanation:
                "Since most sales take 5+ touches, one unanswered email is far from a final no, a polite follow-up is the expected next step, not a nuisance.",
              hint: "Recall the statistic about how many touches most sales actually take.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l3-q3",
              type: "true-false",
              prompt: "You should wait for the other person to bring up next steps rather than asking directly for the close.",
              correctBool: false,
              explanation:
                "Asking directly for the close, clearly and without pressure, moves the process forward faster than hoping the other person raises it on their own.",
              hint: "What does the teach card say about who should initiate the close?",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l3-q4",
              type: "fill-in",
              prompt: "Fill in the blank: Most people give up after just ___ follow-up attempt.",
              accept: ["1", "one"],
              explanation: "Most people stop after one attempt, even though most sales actually require 5 or more touches, persistence is often the real advantage.",
              hint: "It's a single-digit number, and it's small.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u2-l4",
          unitId: "sales-networking-u2",
          courseId: "sales-networking",
          order: 4,
          title: "Unit 2 Challenge: Sell Without Being Salesy",
          difficulty: "Intermediate",
          kind: "challenge",
          xp: 85,
          summary: "Show you can discover, handle pushback, follow up, and close.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u2-l4-t1",
              title: "Recap: sell like a helper, not a pitcher",
              body: "Discovery before pitching, acknowledge-clarify-respond for objections, persistence through follow-ups, and a direct close, that's the whole loop. Skip any step and deals stall.",
            },
            {
              kind: "question",
              id: "sales-networking-u2-l4-q1",
              type: "scenario",
              prompt: "You're pitching a campus print shop to sponsor your entrepreneurship club. They say, 'We already sponsor another club.' What's the best response?",
              context: "This is your first real conversation with the shop's owner, and you haven't asked any questions yet.",
              options: [
                "\"Oh okay, never mind then.\"",
                "\"Got it, is it more that your sponsorship budget is maxed out, or that the other club fits your goals better right now?\"",
                "\"Well, our club is way better than theirs.\"",
                "\"Can you cancel that sponsorship and give it to us instead?\"",
              ],
              correctIndex: 1,
              explanation:
                "This acknowledges the objection and clarifies what's actually behind it, budget versus fit, before responding, which often uncovers room for a smaller or different kind of deal.",
              hint: "Acknowledge, then clarify what the real constraint is before responding.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l4-q2",
              type: "mcq",
              prompt: "Which sequence best represents the full sales loop taught in this unit?",
              options: [
                "Pitch, argue, discount, hope",
                "Discover their problem, pitch to it, handle objections, follow up, ask for the close",
                "Ask for the close immediately, then discover their problem",
                "Send one email and wait",
              ],
              correctIndex: 1,
              explanation:
                "The full loop starts with discovery so the pitch is targeted, handles pushback with acknowledge-clarify-respond, persists through follow-ups, and ends with a direct ask.",
              hint: "Which order builds on itself instead of skipping straight to the ask?",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l4-q3",
              type: "true-false",
              prompt: "If a sponsor doesn't reply to your first outreach email, it's statistically likely they're just not interested.",
              correctBool: false,
              explanation:
                "Since roughly 80% of sales take 5+ touches, one unanswered email says very little about actual interest, follow-up is expected, not desperate.",
              hint: "Recall the follow-up statistic from this unit.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l4-q4",
              type: "fill-in",
              prompt: "Fill in the blank: When someone says a price is 'too expensive,' it usually really means the ___ isn't clear yet.",
              accept: ["value"],
              explanation: "Price objections are frequently value objections in disguise, clarifying almost always reveals whether it's really about the number or about unclear return.",
              hint: "It's the thing your pitch is supposed to build before you ever mention price.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u2-l4-q5",
              type: "scenario",
              prompt: "You've addressed all objections and the sponsor seems genuinely interested but hasn't said yes. What should you do?",
              context: "You've had two good conversations with a local business about a $300 sponsorship, and every objection they raised has been resolved.",
              options: [
                "Keep talking about other topics and hope they bring it up",
                "Directly ask something like, 'Does it make sense to move forward with the sponsorship?'",
                "Assume silence means no and stop contacting them",
                "Wait another month before saying anything else",
              ],
              correctIndex: 1,
              explanation:
                "After objections are resolved, asking directly for the close is what actually moves a warm conversation into a signed deal instead of letting it stall indefinitely.",
              hint: "Recall the 'ask for the close directly' teach card from this unit.",
              xp: 15,
            },
          ],
        },
      ],
    },
    // ─────────────────────────────────────────────────────────────────
    // Unit 3: A Network That Compounds
    // ─────────────────────────────────────────────────────────────────
    {
      id: "sales-networking-u3",
      courseId: "sales-networking",
      order: 3,
      title: "A Network That Compounds",
      subtitle: "Informational interviews, weak ties, and staying on people's radar",
      lessons: [
        {
          id: "sales-networking-u3-l1",
          unitId: "sales-networking-u3",
          courseId: "sales-networking",
          order: 1,
          title: "Informational Interviews",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "How to ask for and run a short conversation that builds real relationships.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u3-l1-t1",
              title: "Keep the ask small: 15-20 minutes",
              body: "An informational interview is a short, low-commitment conversation to learn about someone's path, not a job interview in disguise. Asking for 15-20 minutes signals respect for their time and makes it much easier for them to say yes.",
              example:
                "\"Would you have 15 minutes in the next couple weeks for a few questions about how you moved from audit into corporate strategy?\"",
            },
            {
              kind: "teach",
              id: "sales-networking-u3-l1-t2",
              title: "Never ask for a job directly",
              body: "The moment an informational interview turns into a job ask, it stops feeling like a conversation and starts feeling like a pitch, which changes how the other person shows up. Come prepared with specific questions about their path, decisions, and lessons instead.",
              analogy: "It's the difference between asking someone to coffee to hear their story versus asking them to hire you before you've even sat down.",
            },
            {
              kind: "question",
              id: "sales-networking-u3-l1-q1",
              type: "mcq",
              prompt: "What's the ideal length to ask for in an informational interview request?",
              options: ["5 minutes", "15-20 minutes", "1 hour", "A full afternoon"],
              correctIndex: 1,
              explanation:
                "15-20 minutes is short enough to feel low-commitment and easy to grant, while still being long enough for a handful of real questions.",
              hint: "It should feel easy to say yes to on a busy day.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l1-q2",
              type: "true-false",
              prompt: "It's fine to directly ask for a job during an informational interview if the conversation is going well.",
              correctBool: false,
              explanation:
                "Asking for a job directly changes the nature of the conversation and can make the person feel used, the goal is a genuine conversation, not a hidden pitch.",
              hint: "Think about how it would feel to realize the 'informational' chat was really a job pitch.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l1-q3",
              type: "scenario",
              prompt: "How should you close out an informational interview?",
              context:
                "You just had a great 20-minute call with an alum working in consulting, and she shared a lot of specific advice about breaking into the industry.",
              options: [
                "Ask her outright if she can get you a job at her firm",
                "Thank her, ask if there's anyone else she'd suggest you talk to, and follow up with a specific thank-you afterward",
                "End the call and never speak to her again",
                "Ask her to review your resume line by line right then",
              ],
              correctIndex: 1,
              explanation:
                "Thanking her, asking for further connections, and following up keeps the relationship going without turning the conversation into an ask she didn't sign up for.",
              hint: "The goal is to keep the relationship open, not to extract a job on the spot.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l1-q4",
              type: "fill-in",
              prompt: "Fill in the blank: An informational interview should never turn into a direct ask for a ___.",
              accept: ["job"],
              explanation: "Keeping the conversation focused on learning, not a job ask, is what makes people willing to say yes and be genuinely helpful.",
              hint: "It's the thing that would turn a friendly chat into a pitch.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u3-l2",
          unitId: "sales-networking-u3",
          courseId: "sales-networking",
          order: 2,
          title: "Coffee-Chat Mechanics",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Research, questions, and the thank-you that makes people remember you.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u3-l2-t1",
              title: "Research them before you show up",
              body: "Spend 10-15 minutes on someone's LinkedIn, recent posts, or company before a coffee chat. It lets you skip surface-level questions and ask about the parts of their path that Google can't answer.",
            },
            {
              kind: "teach",
              id: "sales-networking-u3-l2-t2",
              title: "One memorable question beats ten generic ones",
              body: "A specific, well-researched question, about a decision they made, a risk they took, a pivot in their career, sticks with people far more than a list of generic 'what's your day like' questions.",
              example:
                "Instead of 'what's your job like,' try: 'You went from a big-4 firm to a startup, what almost made you not take that risk?'",
            },
            {
              kind: "teach",
              id: "sales-networking-u3-l2-t3",
              title: "Send a same-day thank-you",
              body: "A thank-you sent the same day, referencing something specific they said, shows you were actually listening and keeps you memorable while the conversation is still fresh in their mind.",
            },
            {
              kind: "question",
              id: "sales-networking-u3-l2-q1",
              type: "mcq",
              prompt: "What makes a coffee-chat thank-you note effective?",
              options: [
                "Sending it a week later so you don't seem too eager",
                "Sending it the same day and referencing something specific from the conversation",
                "Keeping it generic so it works for anyone",
                "Only sending one if they ask for it",
              ],
              correctIndex: 1,
              explanation:
                "A same-day, specific thank-you shows genuine engagement and reinforces the relationship while the conversation is still top of mind for both of you.",
              hint: "Timing and specificity both matter here.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l2-q2",
              type: "scenario",
              prompt: "Which question would make the best impression in a coffee chat?",
              context:
                "You're meeting with a recent grad from your school who now works in commercial real estate. You looked at her LinkedIn beforehand and saw she switched firms after two years.",
              options: [
                "\"What's a typical day like for you?\"",
                "\"You switched firms after just two years, what made you decide it was the right move, and what would you do differently?\"",
                "\"Is real estate a good major?\"",
                "\"Can you introduce me to your boss?\"",
              ],
              correctIndex: 1,
              explanation:
                "This question is specific, shows you did research, and invites a real story instead of a generic answer she's given a dozen times before.",
              hint: "The best question references something specific you found in your research.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l2-q3",
              type: "true-false",
              prompt: "Doing a little research beforehand lets you ask better, more specific questions in a coffee chat.",
              correctBool: true,
              explanation:
                "Research lets you skip questions Google could answer and instead ask about decisions, risks, or pivots, the parts of someone's story that are actually memorable to discuss.",
              hint: "Recall the point about research letting you skip surface-level questions.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l2-q4",
              type: "fill-in",
              prompt: "Fill in the blank: A thank-you note should be sent the ___ day and reference something specific.",
              accept: ["same"],
              explanation: "Sending it the same day keeps the conversation fresh and shows you valued their time enough to follow up right away.",
              hint: "It's about how quickly you should send it.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u3-l3",
          unitId: "sales-networking-u3",
          courseId: "sales-networking",
          order: 3,
          title: "Weak Ties Win",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Why acquaintances open more doors than close friends, and how to stay one.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u3-l3-t1",
              title: "Your close friends already know what you know",
              body: "Sociologist Mark Granovetter found that most job leads and opportunities come from weak ties, acquaintances, not close friends. Close friends run in the same circles as you, so they mostly hear about the same things you already hear about.",
              example:
                "The internship lead that actually lands is more likely to come from a classmate you've spoken to twice than from your roommate of three years.",
            },
            {
              kind: "teach",
              id: "sales-networking-u3-l3-t2",
              title: "Give first, ask later",
              body: "Sharing a relevant article, congratulating someone on a promotion, or introducing two people who should know each other keeps a weak tie warm without asking for anything. When you eventually do need something, you're not starting from zero.",
              analogy: "Think of your network like a garden, you can't just show up wanting a harvest if you've never watered anything.",
            },
            {
              kind: "teach",
              id: "sales-networking-u3-l3-t3",
              title: "Referrals beat cold applications",
              body: "A referral from someone inside a company converts into an interview far more often than a cold application into the same job, because it skips the resume pile and comes with built-in trust.",
            },
            {
              kind: "question",
              id: "sales-networking-u3-l3-q1",
              type: "mcq",
              prompt: "According to Granovetter's research, where do most job opportunities actually come from?",
              options: [
                "Close friends and family",
                "Weak ties, acquaintances rather than close friends",
                "Random cold applications",
                "College career centers exclusively",
              ],
              correctIndex: 1,
              explanation:
                "Weak ties tend to move in different circles than you, so they're exposed to information and opportunities your close friends usually aren't.",
              hint: "Think about who is more likely to know something you don't already know.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l3-q2",
              type: "true-false",
              prompt: "Close friends are statistically more likely to be the source of a new job lead than casual acquaintances.",
              correctBool: false,
              explanation:
                "Because close friends share your same circles and information, weak ties, acquaintances, are more likely to expose you to opportunities you haven't already heard about.",
              hint: "Recall Granovetter's 'strength of weak ties' finding.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l3-q3",
              type: "scenario",
              prompt: "What's the best way to stay in touch with a weak tie between asks?",
              context:
                "You met an alum at a networking event six months ago. You haven't needed anything from her since, but you'd like to keep the relationship alive.",
              options: [
                "Don't reach out until you need something specific from her",
                "Occasionally send her a relevant article or congratulate her on a work update, with no ask attached",
                "Ask her to grab coffee every single week",
                "Only interact with her posts once you need a favor",
              ],
              correctIndex: 1,
              explanation:
                "Giving small, no-strings-attached value keeps the relationship warm, so when you do need to ask for something later, you're not reaching out cold.",
              hint: "Think about the 'give first' principle from this lesson.",
              xp: 10,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l3-q4",
              type: "fill-in",
              prompt: "Fill in the blank: A ___ from someone inside a company converts to an interview far more often than a cold application.",
              accept: ["referral"],
              explanation: "Referrals carry built-in trust and often skip the resume pile entirely, which is why they convert at much higher rates than cold applications.",
              hint: "It's when someone inside vouches for you.",
              xp: 10,
            },
          ],
        },
        {
          id: "sales-networking-u3-l4",
          unitId: "sales-networking-u3",
          courseId: "sales-networking",
          order: 4,
          title: "Unit 3 Challenge: A Network That Compounds",
          difficulty: "Advanced",
          kind: "challenge",
          xp: 95,
          summary: "Show you can build, run, and sustain a network that pays off over years, not weeks.",
          cards: [
            {
              kind: "teach",
              id: "sales-networking-u3-l4-t1",
              title: "Recap: small asks, real research, consistent giving",
              body: "Informational interviews stay short and never ask for a job. Coffee chats run on research and one great question. Weak ties open the most doors, and giving first is what keeps any relationship compounding instead of going cold.",
            },
            {
              kind: "question",
              id: "sales-networking-u3-l4-q1",
              type: "scenario",
              prompt: "You're 12 minutes into a 15-minute informational interview and it's going great. What should you do?",
              context: "The alum has shared a lot of useful, specific advice and seems genuinely engaged in the conversation.",
              options: [
                "Ask her directly if she can get you an interview at her company",
                "Respect the time you asked for, wrap up with a couple more questions, and thank her, you can always ask to reconnect later",
                "Keep going for another 30 minutes without checking in",
                "Immediately ask for 5 more contacts to reach out to",
              ],
              correctIndex: 1,
              explanation:
                "Honoring the time you originally asked for shows respect and keeps the relationship easy to continue, the job ask was never supposed to be part of this conversation anyway.",
              hint: "What was the original agreed-upon length, and what should never come up in this type of conversation?",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l4-q2",
              type: "mcq",
              prompt: "Why do weak ties tend to produce more opportunities than close friends?",
              options: [
                "Weak ties have more free time",
                "Weak ties move in different circles and are exposed to information your close friends don't have",
                "Weak ties are more likely to owe you a favor",
                "Close friends are too busy to help",
              ],
              correctIndex: 1,
              explanation:
                "Because close friends often share your same social and professional circles, weak ties are statistically more likely to be your bridge to genuinely new information and opportunities.",
              hint: "Think about what's actually different between your close friends' networks and an acquaintance's network.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l4-q3",
              type: "true-false",
              prompt: "A thank-you note sent a week after a coffee chat is just as effective as one sent the same day.",
              correctBool: false,
              explanation:
                "A same-day thank-you referencing something specific keeps you top of mind while the conversation is fresh, waiting a week weakens that effect significantly.",
              hint: "Recall the timing advice from the coffee-chat lesson.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l4-q4",
              type: "fill-in",
              prompt: "Fill in the blank: You should never directly ask for a ___ during an informational interview.",
              accept: ["job"],
              explanation: "Keeping informational interviews free of a direct job ask is what makes people comfortable being open and helpful in the first place.",
              hint: "It's the same answer as the fill-in from the first lesson in this unit.",
              xp: 15,
            },
            {
              kind: "question",
              id: "sales-networking-u3-l4-q5",
              type: "scenario",
              prompt: "Which behavior best reflects 'giving first' in a real network?",
              context:
                "You just saw that an acquaintance from a networking event got promoted, and separately you read an article that reminded you of a project she once mentioned.",
              options: [
                "Wait until you need a favor, then mention both things to warm her up",
                "Send a short congrats message on the promotion and separately share the article with a note on why it made you think of her project",
                "Ignore both since you don't need anything from her right now",
                "Ask her to introduce you to her manager immediately",
              ],
              correctIndex: 1,
              explanation:
                "Reaching out with genuine, no-ask value, a congrats, a relevant article, is exactly what keeps a weak tie warm and compounding over time.",
              hint: "Recall the 'give first' teach card and what it means to add value with no ask attached.",
              xp: 15,
            },
          ],
        },
      ],
    },
  ],
};
