import type { Course } from "@/lib/types";

export const ventureCapitalCourse: Course = {
  id: "venture-capital",
  title: "Venture Capital",
  tagline: "Learn how billion-dollar bets actually get made, and how to think like the people making them.",
  description:
    "Venture capital funds the riskiest, highest-upside companies in the world, from campus startups to the next trillion-dollar tech giant. This course breaks down how VC funds actually work, how deals get priced and diluted, and how to evaluate a startup the way an investor would, including how students break into the industry themselves.",
  category: "Investing",
  icon: "Landmark",
  color: "from-cyan-400 to-blue-500",
  accent: "cyan-300",
  order: 8,
  unlockLevel: 4,
  units: [
    // ────────────────────────────────────────────────────────────────
    // UNIT 1: How VC Actually Works
    // ────────────────────────────────────────────────────────────────
    {
      id: "venture-capital-u1",
      courseId: "venture-capital",
      order: 1,
      title: "How VC Actually Works",
      subtitle: "What venture capital is, who's actually paying for it, and why the math is so extreme",
      lessons: [
        {
          id: "venture-capital-u1-l1",
          unitId: "venture-capital-u1",
          courseId: "venture-capital",
          order: 1,
          title: "What Venture Capital Actually Is",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Why VC exists, and why most businesses, even great ones, should never raise it.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u1-l1-t1",
              title: "Venture Capital, Defined",
              body: "VC is money that professional investors give to very early, very risky startups in exchange for equity (ownership), betting that a small handful of those startups will grow huge enough to make up for all the ones that fail.",
              example: "A firm invests $500k in a college app startup for 10% ownership, hoping it's worth $50M+ someday, and accepting it might be worth $0.",
            },
            {
              kind: "teach",
              id: "venture-capital-u1-l1-t2",
              title: "Not Every Business Should Raise VC",
              body: "VCs need companies that can plausibly become huge, think $1B+, fast, because their entire model depends on a few massive wins. A profitable local coffee shop chain is a great business but a terrible VC bet, because it can't realistically grow 100x in five years.",
              analogy: "VC is like a talent scout looking only for future superstars. Solid role players are still valuable, they should just fund themselves with revenue or loans, not give up equity chasing a scout who isn't looking for them.",
            },
            {
              kind: "question",
              id: "venture-capital-u1-l1-q1",
              type: "mcq",
              prompt: "Which of these is the best fit for venture capital funding?",
              options: [
                "A laundromat with steady, predictable local revenue",
                "A well-run family restaurant with loyal regulars",
                "A software startup building an AI tool for a global $50B market",
                "A personal blog earning steady ad revenue",
              ],
              correctIndex: 2,
              explanation: "VCs look for startups that could realistically become massive, fast-growing companies in a huge market, the laundromat, restaurant, and blog are all fine businesses, but none can plausibly 100x in a few years.",
              hint: "Think about which option has the biggest possible market and the fastest possible growth ceiling.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l1-q2",
              type: "true-false",
              prompt: "Most businesses, even good ones, should never raise venture capital.",
              correctBool: true,
              explanation: "VC is a narrow fit for high-growth, big-market companies. Most profitable small businesses are better off with revenue, savings, or loans, since giving up equity is expensive and VC investors expect explosive growth.",
              hint: "VC firms need a shot at 100x returns, most solid businesses simply can't grow that fast.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l1-q3",
              type: "scenario",
              context: "Maria runs a bakery that nets $80k profit a year and wants to open two more locations for $150k total. Her roommate Dev built a video-editing AI tool used by only 3 people so far, but it could theoretically serve millions of creators worldwide.",
              prompt: "Which of them is the better fit for venture capital, even though Maria's business is more successful today?",
              options: [
                "Maria, because her bakery already makes money",
                "Dev, because his product has a much bigger potential market and growth ceiling",
                "Neither, VCs only fund companies that are already profitable",
                "Both equally, since VCs just care about current revenue",
              ],
              correctIndex: 1,
              explanation: "VCs care far more about the size of the possible outcome than current profitability. Dev's tool, despite having almost no users today, has a shot at a massive global market, exactly what VC math requires.",
              hint: "VCs aren't investing in what a company is today, they're investing in what it could become.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l1-q4",
              type: "fill-in",
              prompt: "In VC, investors give startups cash in exchange for ___ in the company.",
              accept: ["equity", "ownership", "equity stake", "shares"],
              explanation: "VC firms don't lend money like a bank, they buy a piece of ownership (equity) in the startup, betting its value will grow.",
              hint: "It's the same thing you'd own if you bought stock.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u1-l2",
          unitId: "venture-capital-u1",
          courseId: "venture-capital",
          order: 2,
          title: "Fund Mechanics: LPs, GPs, and 2-and-20",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Where VC money actually comes from, and how the people managing it get paid.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u1-l2-t1",
              title: "Where VC Money Comes From",
              body: "VC firms don't invest their own money, they raise a 'fund' from Limited Partners (LPs) like pension funds, university endowments, and wealthy individuals. The General Partners (GPs) who run the firm then decide which startups to invest in.",
              example: "A $100M fund might have LPs like a state pension fund and a few family offices, while 3-5 GPs actually pick and manage the startup investments.",
            },
            {
              kind: "teach",
              id: "venture-capital-u1-l2-t2",
              title: "The 2-and-20 Model",
              body: "Most VC firms charge LPs a 2% annual management fee on the fund to cover salaries and expenses, plus 20% of the profits once the fund cashes out, known as 'carry.'",
              analogy: "Think of GPs like fund managers who get a salary (the 2%) to do the job, plus a big bonus (the 20% of profit) only if they actually make money for their LPs.",
            },
            {
              kind: "teach",
              id: "venture-capital-u1-l2-t3",
              title: "Funds Have a 10-Year Life",
              body: "A typical VC fund makes new investments over its first 3-5 years, then spends the rest of its roughly 10-year life helping startups grow and waiting for exits, acquisitions or IPOs, to return cash to LPs.",
              example: "A fund raised in 2020 might make its last new investment around 2024, then aim to return most capital to LPs by 2030.",
            },
            {
              kind: "question",
              id: "venture-capital-u1-l2-q1",
              type: "mcq",
              prompt: "In a VC fund, who actually contributes most of the money that gets invested into startups?",
              options: [
                "The General Partners (GPs)",
                "The Limited Partners (LPs)",
                "The startup founders",
                "The federal government",
              ],
              correctIndex: 1,
              explanation: "LPs, pensions, endowments, wealthy individuals, supply the bulk of the fund's capital. GPs manage that capital and make the investment decisions.",
              hint: "GPs run the fund day-to-day, but they're mostly investing someone else's money.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l2-q2",
              type: "fill-in",
              prompt: "The '20' in '2-and-20' refers to the percentage of ___ the GPs keep after a successful exit.",
              accept: ["profit", "profits", "the profits", "gains"],
              explanation: "The 20% 'carry' is a cut of the fund's profits, paid to GPs only after they've actually made money for their LPs.",
              hint: "It's a performance bonus, not a flat fee.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l2-q3",
              type: "true-false",
              prompt: "A VC fund typically keeps making brand-new investments throughout its entire 10-year life.",
              correctBool: false,
              explanation: "Most funds stop writing checks into new startups after about 3-5 years, then spend the rest of their life supporting existing portfolio companies and working toward exits.",
              hint: "Think about the difference between the 'investing period' and the rest of the fund's life.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l2-q4",
              type: "mcq",
              prompt: "What is the 2% annual management fee in '2-and-20' primarily meant to cover?",
              options: [
                "Founder salaries at portfolio companies",
                "The GPs' operating costs, like salaries and office expenses",
                "Taxes owed by the LPs",
                "Marketing budgets for startups",
              ],
              correctIndex: 1,
              explanation: "The management fee keeps the firm running, paying GP salaries and expenses, regardless of whether the fund's investments have paid off yet.",
              hint: "It's paid every year, win or lose, so it's not tied to investment performance.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u1-l3",
          unitId: "venture-capital-u1",
          courseId: "venture-capital",
          order: 3,
          title: "The Power Law and Startup Stages",
          difficulty: "Beginner",
          kind: "lesson",
          xp: 25,
          summary: "Why VCs are fine with most bets failing, and how startups raise money in stages.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u1-l3-t1",
              title: "The Power Law: A Few Winners Carry the Fund",
              body: "In VC, most startups fail or return little, but one or two massive winners in a portfolio can return the entire fund and then some. This lopsided pattern is called the power law, it's nothing like a normal bell curve of outcomes.",
              example: "A firm invests in 100 startups: 60 fail completely, 35 return modest money, but 1 becomes worth $2B and single-handedly returns 10x the whole fund.",
            },
            {
              kind: "teach",
              id: "venture-capital-u1-l3-t2",
              title: "Why VCs Fund So Many Long Shots",
              body: "Because true winners are rare and huge, VCs deliberately build large portfolios and expect most individual bets to fail. They aren't hunting for safe, sure things, they're hunting for outliers.",
              analogy: "It's like buying many tickets in a game where a few tickets can pay out 1,000x, losing on most of them is expected, and totally fine, as long as one big one hits.",
            },
            {
              kind: "teach",
              id: "venture-capital-u1-l3-t3",
              title: "Funding Stages: Pre-Seed to Series C",
              body: "Startups typically raise money in stages as they hit milestones: pre-seed (roughly $50k-$500k, just an idea and a team), seed (roughly $1M-$4M, early product and users), Series A (roughly $5M-$15M, proven traction), then Series B/C to scale a working business further.",
              example: "A campus startup might raise a $150k pre-seed round from angels, then a $2.5M seed round once it hits 10,000 users.",
            },
            {
              kind: "question",
              id: "venture-capital-u1-l3-q1",
              type: "scenario",
              context: "A VC fund invests $200k each in 50 startups. 40 of them fail and return $0. 9 return roughly what was invested. 1 becomes a breakout success that alone returns $40M to the fund.",
              prompt: "What pattern does this outcome best illustrate?",
              options: [
                "Diversification failure, the fund should have picked fewer startups",
                "The power law, a single outlier drives almost all the fund's returns",
                "A balanced bell curve of similar-sized outcomes",
                "Proof that VC is mostly a losing strategy",
              ],
              correctIndex: 1,
              explanation: "This is a textbook power-law outcome: the vast majority of investments contribute little or nothing, while one massive winner drives nearly all of the fund's returns.",
              hint: "Look at how much of the total return came from just one company.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l3-q2",
              type: "mcq",
              prompt: "Which funding stage typically involves check sizes of about $1M-$4M for a startup with an early product and some real users?",
              options: ["Pre-seed", "Seed", "Series B", "Series C"],
              correctIndex: 1,
              explanation: "Seed rounds usually fund a startup that has moved past just an idea, it has an early product and some traction, but isn't yet proven at scale.",
              hint: "Pre-seed is idea-stage; this stage comes right after that.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l3-q3",
              type: "true-false",
              prompt: "VCs generally expect most of their individual startup investments to fail.",
              correctBool: true,
              explanation: "The power law means most bets are expected to return little or nothing, the fund's success depends on the rare huge winner, not on every investment paying off.",
              hint: "Revisit how the power law shapes VC expectations.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l3-q4",
              type: "fill-in",
              prompt: "The pattern where one huge winner returns more than all other investments combined is called the ___.",
              accept: ["power law", "power-law"],
              explanation: "This lopsided outcome distribution, a few extreme winners dominating the returns, is known as the power law.",
              hint: "It's the opposite of a normal, evenly-spread bell curve.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u1-l4",
          unitId: "venture-capital-u1",
          courseId: "venture-capital",
          order: 4,
          title: "Unit 1 Challenge: VC Fundamentals",
          difficulty: "Beginner",
          kind: "challenge",
          xp: 75,
          summary: "Prove you understand what VC is, how funds are structured, and why the power law rules everything.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u1-l4-t1",
              title: "Quick Recap",
              body: "VC funds high-growth, big-market startups using money raised from LPs and managed by GPs under a 2-and-20 model. Because most bets fail, VCs rely on the power law, one huge winner carrying the whole fund, and startups raise in stages as they prove themselves.",
            },
            {
              kind: "question",
              id: "venture-capital-u1-l4-q1",
              type: "scenario",
              context: "A $50M VC fund eventually returns $150M total to its LPs, meaning $100M in profit above what was invested. The fund charges the standard 20% carry on profits.",
              prompt: "How much carry do the GPs collect?",
              options: ["$10M", "$20M", "$30M", "$100M"],
              correctIndex: 1,
              explanation: "Carry is 20% of profit, not of the total returned. Profit was $100M, so carry = 20% × $100M = $20M.",
              hint: "Carry applies to the profit only, not the full amount returned to LPs.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l4-q2",
              type: "mcq",
              prompt: "Which statement about venture capital is FALSE?",
              options: [
                "VCs expect most portfolio companies to fail or underperform",
                "A VC fund is usually raised entirely from the GPs' own personal savings",
                "LPs include pensions, endowments, and wealthy individuals",
                "Startups typically raise money in stages as they hit milestones",
              ],
              correctIndex: 1,
              explanation: "VC funds are raised mostly from outside LPs, not from the GPs' personal money, the GPs manage the fund and typically contribute only a small slice of it themselves.",
              hint: "Think about who LPs are and why they exist.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l4-q3",
              type: "true-false",
              prompt: "A profitable small business that can't realistically grow 100x is generally a bad fit for venture capital, even if it's a great business.",
              correctBool: true,
              explanation: "VC math depends on huge, rare winners. A stable, modestly-growing business, however well-run, doesn't fit that model and is better served by loans or reinvested revenue.",
              hint: "Recall the difference between a 'good business' and a 'VC-fundable business.'",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l4-q4",
              type: "fill-in",
              prompt: "The earliest, smallest funding stage, often just an idea and a founding team, is called ___.",
              accept: ["pre-seed", "pre seed", "preseed"],
              explanation: "Pre-seed rounds fund startups before they have much more than an idea, a team, and maybe an early prototype.",
              hint: "It comes before even the 'seed' stage.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u1-l4-q5",
              type: "mcq",
              prompt: "Why do VC firms deliberately invest in many startups instead of just one or two they're most confident in?",
              options: [
                "Because diversification guarantees a profit",
                "Because most bets are expected to fail, and they need enough shots for a rare huge winner to emerge",
                "Because LPs require a minimum number of investments by law",
                "Because smaller checks are always more profitable than large ones",
              ],
              correctIndex: 1,
              explanation: "Since most individual startups will fail or underperform, VCs need a wide enough portfolio to have a real shot at catching the rare power-law winner.",
              hint: "This connects directly back to how the power law works.",
              xp: 15,
            },
          ],
        },
      ],
    },
    // ────────────────────────────────────────────────────────────────
    // UNIT 2: Deals & Dilution
    // ────────────────────────────────────────────────────────────────
    {
      id: "venture-capital-u2",
      courseId: "venture-capital",
      order: 2,
      title: "Deals & Dilution",
      subtitle: "Valuation math, SAFEs, term sheets, and what happens to a founder's ownership over time",
      lessons: [
        {
          id: "venture-capital-u2-l1",
          unitId: "venture-capital-u2",
          courseId: "venture-capital",
          order: 1,
          title: "Pre-Money vs Post-Money Valuation",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "The two numbers that decide how much of the company an investor actually owns.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u2-l1-t1",
              title: "Pre-Money and Post-Money, Defined",
              body: "Pre-money valuation is what a startup is worth right before an investment. Post-money valuation is simply pre-money plus the new cash raised.",
              example: "A startup is valued at $8M pre-money. An investor puts in $2M, so post-money valuation = $8M + $2M = $10M.",
            },
            {
              kind: "teach",
              id: "venture-capital-u2-l1-t2",
              title: "How Ownership Gets Calculated",
              body: "An investor's ownership percentage equals the amount they invest divided by the post-money valuation, not the pre-money valuation.",
              example: "Investing $2M into a company with a $10M post-money valuation gives the investor $2M ÷ $10M = 20% ownership.",
            },
            {
              kind: "question",
              id: "venture-capital-u2-l1-q1",
              type: "mcq",
              prompt: "A startup has a pre-money valuation of $4M and raises $1M. What is its post-money valuation?",
              options: ["$5M", "$4M", "$3M", "$6M"],
              correctIndex: 0,
              explanation: "Post-money = pre-money + amount raised = $4M + $1M = $5M.",
              hint: "Post-money is always pre-money plus the new money coming in.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l1-q2",
              type: "scenario",
              context: "A campus startup is valued at $6M pre-money and raises $1.5M from a VC firm.",
              prompt: "Roughly what percentage of the company does the investor now own?",
              options: ["10%", "20%", "25%", "15%"],
              correctIndex: 1,
              explanation: "Post-money = $6M + $1.5M = $7.5M. Ownership = $1.5M ÷ $7.5M = 20%.",
              hint: "First find the post-money valuation, then divide the investment by it.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l1-q3",
              type: "fill-in",
              prompt: "Post-money valuation = pre-money valuation + ___.",
              accept: ["amount raised", "investment amount", "the amount invested", "new money raised", "money raised"],
              explanation: "Post-money is simply the company's value before the round plus whatever new cash the round brings in.",
              hint: "It's the new money that just came into the company.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l1-q4",
              type: "true-false",
              prompt: "Post-money valuation is always lower than pre-money valuation.",
              correctBool: false,
              explanation: "Post-money is pre-money plus the new investment, so it's always higher than (or equal to, if $0 is raised) pre-money, never lower.",
              hint: "Post-money adds money on top of pre-money, it can't shrink the number.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u2-l2",
          unitId: "venture-capital-u2",
          courseId: "venture-capital",
          order: 2,
          title: "SAFEs: Startups' Favorite Shortcut",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "Why so many early rounds skip a formal valuation and use a SAFE instead.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u2-l2-t1",
              title: "What a SAFE Is",
              body: "A SAFE (Simple Agreement for Future Equity) is a contract where an investor gives a startup cash now in exchange for the right to receive equity later, when the startup raises a priced round, no valuation is locked in on the spot.",
              analogy: "A SAFE is like a rain check for equity: you pay now, and you pick up your shares later at a price determined by the terms you agreed to.",
            },
            {
              kind: "teach",
              id: "venture-capital-u2-l2-t2",
              title: "Why Y Combinator Invented SAFEs",
              body: "Y Combinator created the SAFE in 2013 to make early fundraising fast and cheap, by skipping the costly legal negotiation of setting an exact valuation and full term sheet for small early checks.",
              example: "A founder can close a $200k pre-seed SAFE in a matter of days, instead of the weeks a full priced equity round would typically take.",
            },
            {
              kind: "teach",
              id: "venture-capital-u2-l2-t3",
              title: "Valuation Caps and Discounts",
              body: "A valuation cap sets the maximum price at which a SAFE converts to equity, protecting early investors if the company's value skyrockets. A discount instead gives SAFE investors a lower price than later investors, both reward investors for taking risk earliest.",
              example: "A SAFE with a $5M cap means that even if the startup's next priced round is valued at $20M, that SAFE investor still converts as if the company were worth $5M, a far better price.",
            },
            {
              kind: "question",
              id: "venture-capital-u2-l2-q1",
              type: "mcq",
              prompt: "What does SAFE stand for?",
              options: [
                "Simple Agreement for Future Equity",
                "Startup Angel Funding Entity",
                "Secured Asset Financing Equity",
                "Simple Angel Fund Election",
              ],
              correctIndex: 0,
              explanation: "SAFE stands for Simple Agreement for Future Equity, a fast, lightweight way to fund early startups without setting a valuation upfront.",
              hint: "The name literally describes what it does: an agreement for equity you'll receive in the future.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l2-q2",
              type: "scenario",
              context: "A student startup raises $100k on a SAFE with a $4M valuation cap. A year later, it raises a priced Series A at a $16M pre-money valuation.",
              prompt: "Why does the SAFE investor's $4M cap matter so much here?",
              options: [
                "It doesn't matter, SAFEs always convert at the Series A price",
                "It lets the SAFE investor convert as if the company were worth only $4M, getting far more shares for their money than new Series A investors",
                "It means the SAFE investor must pay an extra $12M to keep their stake",
                "It cancels the SAFE since the company grew too much",
              ],
              correctIndex: 1,
              explanation: "The cap protects early believers: since the company grew to a $16M valuation, converting at the lower $4M cap gets the SAFE investor a much bigger ownership stake for the same $100k.",
              hint: "The cap is a ceiling on the price the SAFE investor pays, no matter how high the company's value climbs.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l2-q3",
              type: "true-false",
              prompt: "A SAFE immediately sets a fixed, final valuation for the startup at the moment it's signed.",
              correctBool: false,
              explanation: "That's the whole point of a SAFE, it defers setting an exact valuation until a later priced round, keeping early fundraising fast and simple.",
              hint: "Think about what problem the SAFE was invented to solve.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l2-q4",
              type: "fill-in",
              prompt: "A SAFE can set a maximum conversion price called a valuation ___.",
              accept: ["cap", "valuation cap"],
              explanation: "The valuation cap protects early SAFE investors by capping the price at which their investment converts into equity.",
              hint: "It's the ceiling that protects early investors if the company's value rises a lot.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u2-l3",
          unitId: "venture-capital-u2",
          courseId: "venture-capital",
          order: 3,
          title: "Term Sheets and Dilution",
          difficulty: "Intermediate",
          kind: "lesson",
          xp: 30,
          summary: "What's actually inside a term sheet, and why founders own less with every round.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u2-l3-t1",
              title: "What's in a Term Sheet",
              body: "A term sheet outlines the key deal terms beyond just price: board seats (who controls major decisions), pro-rata rights (the right to invest again in future rounds to maintain ownership %), and liquidation preferences (who gets paid first if the company is sold).",
            },
            {
              kind: "teach",
              id: "venture-capital-u2-l3-t2",
              title: "Liquidation Preference, Simplified",
              body: "A '1x non-participating' liquidation preference means investors get their money back first in a sale before common shareholders split what's left, but they don't also double-dip into that remaining pool on top of getting their money back.",
              example: "An investor who put in $2M with a 1x preference gets at least $2M back before founders or employees see anything, in a modest exit.",
            },
            {
              kind: "teach",
              id: "venture-capital-u2-l3-t3",
              title: "Dilution Across Rounds",
              body: "Each new funding round issues new shares, which shrinks, or 'dilutes', existing owners' percentage, even though the company's total value usually grows at the same time.",
              example: "A founder starts at 100% ownership, drops to around 80-85% after a seed round and an option pool, then to roughly 50-60% by the time Series A closes.",
            },
            {
              kind: "question",
              id: "venture-capital-u2-l3-q1",
              type: "mcq",
              prompt: "What does a 'pro-rata right' let an investor do?",
              options: [
                "Sell their shares early to another investor",
                "Invest again in future rounds to maintain their ownership percentage",
                "Automatically double their liquidation preference",
                "Force the company to IPO within 5 years",
              ],
              correctIndex: 1,
              explanation: "Pro-rata rights let an existing investor put in more money in later rounds specifically to avoid being diluted below their current ownership percentage.",
              hint: "'Pro-rata' means 'in proportion', think about keeping a proportional stake.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l3-q2",
              type: "scenario",
              context: "A founder owns 100% of their startup at launch. After a seed round plus a 10% option pool carved out for employees, they own 82%. In the Series A round, new investors take 20% of the company.",
              prompt: "Approximately what percentage does the founder own after the Series A closes?",
              options: ["~66%", "~50%", "~82%", "~40%"],
              correctIndex: 0,
              explanation: "The founder's 82% gets diluted by the new 20% round: 82% × (1 − 0.20) ≈ 65.6%, roughly 66%.",
              hint: "Apply the new round's dilution percentage to the founder's current stake, not to 100%.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l3-q3",
              type: "true-false",
              prompt: "A '1x non-participating' liquidation preference means investors get their investment back AND an equal share of whatever is left over.",
              correctBool: false,
              explanation: "That describes a 'participating' preference. 'Non-participating' means investors choose either their preference or converting to common shares, they don't get both.",
              hint: "The word 'non-participating' is a clue about what they don't get to do.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l3-q4",
              type: "fill-in",
              prompt: "The gradual shrinking of a founder's ownership percentage as new shares are issued in each round is called ___.",
              accept: ["dilution"],
              explanation: "Dilution happens automatically whenever new shares are created for new investors or an option pool, since the total number of shares grows.",
              hint: "It's the same root word as 'diluting' a drink, spreading the same thing across more volume.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u2-l4",
          unitId: "venture-capital-u2",
          courseId: "venture-capital",
          order: 4,
          title: "Unit 2 Challenge: Deals & Dilution",
          difficulty: "Intermediate",
          kind: "challenge",
          xp: 80,
          summary: "Test your grip on valuation math, SAFEs, term sheets, and dilution across rounds.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u2-l4-t1",
              title: "Quick Recap",
              body: "Post-money valuation sets an investor's ownership percentage; SAFEs use caps and discounts to reward early risk without pricing the round upfront; term sheets set control and payout terms; and every new round dilutes existing owners, even as the company's value grows.",
            },
            {
              kind: "question",
              id: "venture-capital-u2-l4-q1",
              type: "scenario",
              context: "A startup is valued at $9M pre-money. A VC firm invests $3M in the round.",
              prompt: "What percentage of the company does the VC firm own after the round closes?",
              options: ["20%", "25%", "33%", "30%"],
              correctIndex: 1,
              explanation: "Post-money = $9M + $3M = $12M. Ownership = $3M ÷ $12M = 25%.",
              hint: "Find post-money first, then divide the investment by that total.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l4-q2",
              type: "mcq",
              prompt: "A SAFE offers both a valuation cap AND a discount. If the next priced round's valuation is very high, which term protects the investor most?",
              options: [
                "The discount, since it always beats the cap",
                "The valuation cap, since it locks in a much lower conversion price regardless of how high the round prices",
                "Neither matters once a priced round happens",
                "The discount and cap always produce the same result",
              ],
              correctIndex: 1,
              explanation: "When the company's value has grown a lot, the cap (a fixed ceiling price) gives a far better deal than a discount (a percentage off the new, much higher price).",
              hint: "A discount is a percentage off a high number; a cap is a hard ceiling regardless of how high that number goes.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l4-q3",
              type: "true-false",
              prompt: "In a startup sale, holders of a 1x liquidation preference are typically paid out before common shareholders (like founders and employees).",
              correctBool: true,
              explanation: "Liquidation preferences exist specifically to pay preferred (investor) shareholders first, before remaining proceeds go to common shareholders.",
              hint: "This is the entire purpose of a liquidation preference.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l4-q4",
              type: "fill-in",
              prompt: "The right that lets an existing investor put more money into a later round to avoid losing their ownership percentage is called a ___ right.",
              accept: ["pro-rata", "pro rata", "prorata"],
              explanation: "Pro-rata rights let investors maintain their proportional ownership by participating in future rounds.",
              hint: "It literally means 'in proportion.'",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u2-l4-q5",
              type: "mcq",
              prompt: "Which of these is a normal, expected part of a startup's ownership story from founding through Series A?",
              options: [
                "The founder's percentage ownership steadily increases with each round",
                "The founder's percentage ownership decreases with each round, even as the company's total value rises",
                "Ownership percentages never change once the company is founded",
                "Only employees get diluted, founders are always protected from dilution",
              ],
              correctIndex: 1,
              explanation: "Dilution is normal and expected: founders typically drop from 100% toward 50-60% by Series A, even though the company itself is usually worth far more by then.",
              hint: "A smaller slice of a much bigger pie can still be worth more.",
              xp: 15,
            },
          ],
        },
      ],
    },
    // ────────────────────────────────────────────────────────────────
    // UNIT 3: Think Like an Investor
    // ────────────────────────────────────────────────────────────────
    {
      id: "venture-capital-u3",
      courseId: "venture-capital",
      order: 3,
      title: "Think Like an Investor",
      subtitle: "Evaluating startups, sizing markets, spotting red flags, and breaking into VC as a student",
      lessons: [
        {
          id: "venture-capital-u3-l1",
          unitId: "venture-capital-u3",
          courseId: "venture-capital",
          order: 1,
          title: "Evaluating a Startup: Team, Market, Traction",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "The core framework investors use to judge whether a startup is worth backing.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u3-l1-t1",
              title: "The Big Three: Team, Market, Traction",
              body: "VCs mainly evaluate three things: the founding team's ability to execute, the size and growth of the market, and early traction, users, revenue, or growth rate, that proves the idea has real legs.",
            },
            {
              kind: "teach",
              id: "venture-capital-u3-l1-t2",
              title: "TAM, SAM, SOM",
              body: "TAM (Total Addressable Market) is the entire possible market. SAM (Serviceable Addressable Market) is the slice you can realistically reach with your product and channels. SOM (Serviceable Obtainable Market) is what you could realistically capture in the near term.",
              example: "For a college meal-planning app: TAM = all U.S. college students (~19M), SAM = students at schools with dining plans you can integrate with (~6M), SOM = the ~50,000 students you could realistically sign up in year one.",
            },
            {
              kind: "teach",
              id: "venture-capital-u3-l1-t3",
              title: "Why Moat Matters",
              body: "A moat is what stops competitors from copying a startup's success, network effects, proprietary tech, exclusive data, or brand, and VCs look for it because big markets always attract big competition.",
              analogy: "A moat is literally like a castle's moat: the bigger and deeper it is, the harder it is for rivals to storm the business.",
            },
            {
              kind: "question",
              id: "venture-capital-u3-l1-q1",
              type: "mcq",
              prompt: "In market sizing, what does SOM stand for?",
              options: [
                "Serviceable Obtainable Market",
                "Startup Operating Model",
                "Standard Operating Metrics",
                "Serviceable Offered Market",
              ],
              correctIndex: 0,
              explanation: "SOM is the Serviceable Obtainable Market, the realistic slice of the market you can actually capture in the near term.",
              hint: "It's the smallest and most realistic of the three market-sizing numbers.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l1-q2",
              type: "scenario",
              context: "A startup building a budgeting app for grad students tells investors: the TAM is all U.S. adults (~250M), the SAM is U.S. college students (~19M), and the SOM is the 30,000 students they can realistically reach in year one through campus ambassadors.",
              prompt: "Which number should a smart investor weigh most heavily when judging this early-stage pitch?",
              options: [
                "The TAM, since bigger always means better",
                "The SOM, since it reflects what the startup can actually achieve in the near term",
                "The SAM, since it's the average of the other two",
                "None of them, market size doesn't matter at this stage",
              ],
              correctIndex: 1,
              explanation: "TAM sounds impressive but is often disconnected from reality. SOM shows investors the founder actually understands how growth will realistically happen in the near term.",
              hint: "A huge TAM is easy to claim, which number requires the founder to show a realistic plan?",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l1-q3",
              type: "true-false",
              prompt: "A great founding team can matter more to VCs than a slightly better idea from a weaker team.",
              correctBool: true,
              explanation: "Many VCs prioritize team quality because a strong team can pivot and execute through changing markets, while a weak team can waste even a great idea.",
              hint: "Think about which is easier to fix over time: a mediocre idea or a weak team.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l1-q4",
              type: "fill-in",
              prompt: "A sustainable competitive advantage that protects a startup from copycats is called a ___.",
              accept: ["moat", "competitive moat"],
              explanation: "A moat, network effects, proprietary tech, exclusive data, or brand, is what keeps competitors from simply copying a successful startup.",
              hint: "Think of the castle analogy.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u3-l2",
          unitId: "venture-capital-u3",
          courseId: "venture-capital",
          order: 2,
          title: "Market Sizing and Red Flags",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "How to size a market credibly, and the warning signs that make investors walk away.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u3-l2-t1",
              title: "Bottom-Up vs Top-Down Sizing",
              body: "Top-down sizing starts with a big industry number and guesses a slice of it, risky and often inflated. Bottom-up sizing instead builds up from real units, like price times a realistic number of customers you can actually reach, and is far more credible to investors.",
              example: "Top-down: 'The education market is $500B, so we'll capture just 1% = $5B.' Bottom-up: '3,000 colleges × 500 students each × $20/month = $360M realistic revenue ceiling.'",
            },
            {
              kind: "teach",
              id: "venture-capital-u3-l2-t2",
              title: "Red Flags VCs Watch For",
              body: "Warning signs include a 'TAM' that's really just a huge unrelated industry number, founders who haven't talked to a single real customer, and messy 50/50 co-founder splits with no clear tiebreaker, all signal a startup isn't ready or well-structured.",
              example: "A founder claiming 'the global retail market is $5 trillion, we just need 0.1%' without ever describing a real customer is a classic red flag.",
            },
            {
              kind: "question",
              id: "venture-capital-u3-l2-q1",
              type: "mcq",
              prompt: "Which market-sizing approach builds up from real prices and realistic customer counts, rather than slicing a huge industry number?",
              options: ["Top-down", "Bottom-up", "Sideways", "Blended"],
              correctIndex: 1,
              explanation: "Bottom-up sizing starts from real, concrete numbers, like price × realistic customer count, making it far more credible than an arbitrary slice of a giant top-down figure.",
              hint: "It's built 'up' from small, real numbers rather than sliced 'down' from a huge one.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l2-q2",
              type: "scenario",
              context: "A founder pitches: 'The global food industry is worth $8 trillion, so if we get just 0.01% we'll be an $800M company.'",
              prompt: "What red flag does this pitch show?",
              options: [
                "It shows strong, credible bottom-up market sizing",
                "It's an inflated top-down TAM with no real logic for how the company actually gets those customers",
                "It proves the company is already generating revenue",
                "It's a red flag only because $800M is too small a target",
              ],
              correctIndex: 1,
              explanation: "Slicing an enormous, unrelated industry number without explaining a real path to customers is a classic inflated top-down TAM, a major red flag for investors.",
              hint: "Ask yourself: does this pitch explain how they'll actually reach real customers?",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l2-q3",
              type: "true-false",
              prompt: "A 50/50 equity split between co-founders with no tiebreaker mechanism is generally seen as low-risk by VCs.",
              correctBool: false,
              explanation: "A 50/50 split with no clear decision-maker can create deadlock when co-founders disagree, which is a structural red flag investors watch for.",
              hint: "Think about what happens when two equal partners can't agree on a major decision.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l2-q4",
              type: "fill-in",
              prompt: "Sizing a market by multiplying a realistic price by a realistic customer count is called ___-up sizing.",
              accept: ["bottom", "bottom-up"],
              explanation: "Bottom-up sizing builds the market estimate from real, grounded numbers rather than guessing a slice of a huge industry figure.",
              hint: "It's the opposite direction of 'top-down.'",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u3-l3",
          unitId: "venture-capital-u3",
          courseId: "venture-capital",
          order: 3,
          title: "Breaking Into VC as a Student",
          difficulty: "Advanced",
          kind: "lesson",
          xp: 35,
          summary: "Real paths students use to get VC experience, fellowships, sourcing, memos, and scout programs.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u3-l3-t1",
              title: "Campus On-Ramps",
              body: "Students can get real VC experience through campus venture fellowships, student-run investment funds, and scout programs, where an experienced VC pays a student to source promising deals from their own network.",
              example: "A university venture fellowship might have students source 5 startups a semester and present investment memos to a partner for feedback.",
            },
            {
              kind: "teach",
              id: "venture-capital-u3-l3-t2",
              title: "Sourcing and the Investment Memo",
              body: "'Sourcing' means finding promising startups before other investors do, often through your own network. A strong investment memo clearly lays out the team, market, traction, and risks, and explains why this deal deserves a check.",
              example: "A memo might open with 'This team already has 2,000 paying users after 3 months with zero marketing spend,' then walk through market size and key risks.",
            },
            {
              kind: "teach",
              id: "venture-capital-u3-l3-t3",
              title: "Angel Syndicates and Scout Checks",
              body: "An angel syndicate lets many small investors pool money behind one lead investor's deal, while a 'scout' is someone, often a student, given a small pool of a VC firm's money to write small checks into deals they find.",
              analogy: "A scout is like a talent scout for a sports team: you don't own the team, but you get paid or rewarded for finding the next star player.",
            },
            {
              kind: "question",
              id: "venture-capital-u3-l3-q1",
              type: "mcq",
              prompt: "What is 'sourcing' in venture capital?",
              options: [
                "Setting a startup's official valuation",
                "Finding promising startups before other investors do",
                "Filing the legal paperwork for a deal",
                "Auditing a startup's financial statements",
              ],
              correctIndex: 1,
              explanation: "Sourcing is about discovering strong startups early, often through personal networks, before they're widely known to other investors.",
              hint: "Think about what a 'scout' does first, before any deal terms come into play.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l3-q2",
              type: "true-false",
              prompt: "A scout program lets a student invest a VC firm's money into deals they personally find, without being a full-time employee of the firm.",
              correctBool: true,
              explanation: "Scout programs give students or other outsiders a small pool of capital to deploy into deals they source, acting as an extension of the firm's network.",
              hint: "This is one of the more accessible ways students break into VC.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l3-q3",
              type: "scenario",
              context: "A sophomore meets a founder building a campus laundry-pickup app at a pitch night. The founder already has 300 paying users after one month and strong month-over-month growth.",
              prompt: "What's the best next move for the student, if they're trying to build real VC experience?",
              options: [
                "Ignore it, students can't do anything useful with a lead like this",
                "Write a quick investment memo on the startup and bring it to a mentor, fellowship, or fund",
                "Demand equity in the startup immediately in exchange for the introduction",
                "Invest their own tuition money directly into the startup",
              ],
              correctIndex: 1,
              explanation: "Turning a sourced lead into a clear, well-reasoned investment memo and sharing it with a mentor or program is exactly how students build real credibility and experience in VC.",
              hint: "Think about what actually builds a track record without requiring real capital of your own.",
              xp: 10,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l3-q4",
              type: "fill-in",
              prompt: "A written analysis of a startup covering team, market, traction, and risks, used to pitch a deal internally, is called an investment ___.",
              accept: ["memo", "memorandum"],
              explanation: "An investment memo organizes the case for or against a deal, and is a core skill for anyone breaking into VC.",
              hint: "It's a short document, not a legal contract.",
              xp: 10,
            },
          ],
        },
        {
          id: "venture-capital-u3-l4",
          unitId: "venture-capital-u3",
          courseId: "venture-capital",
          order: 4,
          title: "Unit 3 Challenge: Investor Thinking",
          difficulty: "Advanced",
          kind: "challenge",
          xp: 85,
          summary: "The final test, evaluating startups, sizing markets, spotting red flags, and thinking like a scout.",
          cards: [
            {
              kind: "teach",
              id: "venture-capital-u3-l4-t1",
              title: "Quick Recap",
              body: "Investors judge team, market, and traction using tools like TAM/SAM/SOM and bottom-up sizing, while watching for red flags like inflated TAMs and messy cap tables. Students can build real VC skills through sourcing, memos, and scout programs long before they manage a fund.",
            },
            {
              kind: "question",
              id: "venture-capital-u3-l4-q1",
              type: "scenario",
              context: "A founder pitches a campus food-delivery startup: 'Our SOM is 40,000 students across 20 partner campuses, paying $15/month, which we can realistically reach in 18 months through campus ambassadors.'",
              prompt: "What makes this SOM claim more credible than a typical inflated TAM claim?",
              options: [
                "It's a bigger number than most TAM claims",
                "It's grounded in a specific, realistic customer count, price, and go-to-market plan",
                "It uses the word 'realistically,' which automatically makes it true",
                "SOM claims never need to be justified",
              ],
              correctIndex: 1,
              explanation: "This SOM is credible because it's built bottom-up from concrete numbers and a specific plan to reach those customers, exactly what separates real sizing from inflated top-down guesses.",
              hint: "Compare this to a vague 'we'll capture 1% of a trillion-dollar market' claim.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l4-q2",
              type: "mcq",
              prompt: "A founder says their startup has 'no real moat yet, but we're moving fast.' From an investor's perspective, why is a moat still important to ask about?",
              options: [
                "Because without a moat, well-funded competitors can copy the idea once it proves out",
                "Because moats are only relevant after a company goes public",
                "Because moats guarantee a startup will succeed regardless of execution",
                "Because VCs only invest in companies with zero competition",
              ],
              correctIndex: 0,
              explanation: "A moat matters because early traction alone doesn't stop bigger, better-resourced competitors from copying a proven idea, investors want to know what will defend the business over time.",
              hint: "Think about what happens once a good idea is proven to work and other players notice.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l4-q3",
              type: "true-false",
              prompt: "Founders who haven't talked to any real customers yet are generally seen as a red flag by investors, even if their idea sounds exciting.",
              correctBool: true,
              explanation: "Without real customer conversations, a founder's assumptions about the market and product are untested, a key warning sign investors take seriously.",
              hint: "Think about how investors judge whether a founder truly understands their market.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l4-q4",
              type: "fill-in",
              prompt: "The market-sizing figure representing the entire theoretical market for a product, before narrowing to what's realistically reachable, is called the ___.",
              accept: ["tam", "total addressable market"],
              explanation: "TAM (Total Addressable Market) is the biggest, most theoretical number, it's SAM and SOM that narrow it down to something realistic.",
              hint: "It's the first and largest of the three market-sizing letters: T-S-S.",
              xp: 15,
            },
            {
              kind: "question",
              id: "venture-capital-u3-l4-q5",
              type: "mcq",
              prompt: "A student wants to build a track record in VC without having capital of their own to invest. What's the most realistic path from what you've learned?",
              options: [
                "Take out a personal loan to invest in startups directly",
                "Source promising startups, write investment memos, and pursue fellowships or scout programs",
                "Wait until after graduation, since students can't participate in VC at all",
                "Only focus on picking public stocks instead",
              ],
              correctIndex: 1,
              explanation: "Sourcing deals, writing memos, and joining campus fellowships or scout programs are realistic, low-capital ways students build genuine VC experience and credibility.",
              hint: "Recall the campus on-ramps discussed earlier in this unit.",
              xp: 15,
            },
          ],
        },
      ],
    },
  ],
};
